### ISSUE TITLE
Max Subsidy Discussion

### ISSUE THREAD

**Issue by kilpatty** [handshake-org/hsd#100]
After some on going discussion with @boymanjor and others in the dev channel, I wanted to open up this issue just to track the max subsidy number and it's potential change. 

From my understanding, the way to calculate a coin's max supply is the following formula:

```2*(initial-block-reward) * (number of blocks per halving)``` 

For BTC:
 ```2*(50) * (210,000) === 21,000,000```

For the previous testnet:
 ```2*(1000) * (340,000) === 680,000,000``` 

which matches the max subsidy defined here: https://github.com/handshake-org/hsd/blob/master/lib/protocol/consensus.js#L88

Although, with the new testnet the halving was changed from every 340,000 blocks to every 170,000 blocks. This now means that the max subsidy is roughly half what it was from the last testnet. 

HNS testnet3: 
```2*1000 * 170,000 === 340,000,000```

Despite this, the Max_subsidy constant did not change. 

@boymanjor had mentioned that the intention is to keep the max subsidy the same (680 million), and therefore I just wanted to open this issue to centralize the discussion around it. I know I may be missing something in the math, so it would be great to have that correction in one location for others to see. 

Secondly, if the max checks out -> I'm curious which path going forward would be the way to correct it. Would the halving interval be changed back to 340,000 blocks or would the starting reward move from 1000 to 2000.

**Comment by chjj** [comment]
Hmm, yeah. The halving interval was reduced to account for the 10 minute block time. I think we wanted to keep the deflation rate similar to bitcoin (supply runs dry in around 100 years). The next testnet should probably increase the block subsidy to 2000 coins as a base reward.
