### ISSUE TITLE
Add READMEs for Internal Module Folders

### ISSUE THREAD

**Issue by aunyks** [handshake-org/hsd#102]
I think there should be READMEs that provide quick (or descriptive) overview's of the contents of internal modules throughout the project, particularly those in `lib/`. Something similar to LND: [one](https://github.com/lightningnetwork/lnd/tree/master/lnrpc), [two](https://github.com/lightningnetwork/lnd/tree/master/tor), and [three](https://github.com/lightningnetwork/lnd/tree/master/zpay32).  

I think this'd lower the barrier to first PR for new developers looking at the project, as the READMEs could speed up understanding the codebase, how it's organized, and how certain components relate to others.

I'm willing to open PRs for this, should the additions be favorable.

**Comment by boymanjor** [comment]
@aunyks I think this is a great idea! If you want to get started, I can help out with review and answer questions about the codebase.
