### ISSUE TITLE
Mass Name Revocations (or, "what to do if godaddy gets hacked")

### ISSUE THREAD

**Issue by chjj** [handshake-org/hsd#103]
This is something I feel like we've put off for a while, but might be one of the more important parts of this system.

The question has been in the back of a lot of people's minds since day one: what if godaddy or namecheap gets hacked? How does HNS deal with this? We allow for DNSSEC ownership claims from existing nameholders. The majority of the reserved name list is likely to be registered with godaddy or namecheap.

Maybe "hacked" isn't a specific enough description. There are several different scenarios here. I'll outline a few examples:

- Scenario 1: Verisign's signing key is compromised.
- Scenario 2: Godaddy's ZSKs are compromised (or KSKs for that matter).
- Scenario 3: Godaddy's login info and accounts are compromised.

All three of those scenarios have different implications for name claims. Our system needs to be able to recover from the damage caused by any of these scenarios. Handshake is basically dead in the water if it can't recover from a mass name hack from the outside. In particular, this system needs to be able to handle a mass revocation for names in a very simple and scalable manner.

After a long conversation with @josephpoon, I think we came up with an acceptable solution, but it's probably wise to explain _how_ we got there. We iterated through a few ideas over the past year or so.

## Idea 1: Allow higher timestamp RRSIGs to replace and override older ones

Not only override, but invalidate lower timestamp signatures. This was our initial and very naive solution. Long story short, this doesn't account for revocations _directly_. The timestamps on signatures are also untrustworthy and cannot be controlled by users of services like godaddy. Furthermore, it would require some kind of database index for all signatures which came before (very ugly).

## Idea 2: Allow publishing of a DNSKEY revocation proof to chain

Our second idea was better, but still flawed: name claims for reserved names require two proofs to be published, with a 30 day locktime in between. During the 30 day period, a DNSSEC key revocation can be published to chain for any of the keys used in the original proof.

During the second proof's verification, all keys will be checked to see whether they were revoked. Any second proof containing a revoked key will be rejected. Not much performance cost here since checking for a revoked key is much like checking for a UTXO.

There's a few issues here:

1. This would require a new message type to be relayed on the p2p layer (a revocation message).

2. It would require a global database index of revoked keys. This index would be a source of unbounded growth. The revoked keys can never be forgotten. As a result, we would have to add DoS limits for revocations on-chain. This would allow a godaddy hacker to spam the chain before they publicly reveal that they are in posession of godaddy's keys, thereby preventing the actual revocation proofs from being published.

3. Verisign, afilias, or some other DNS giant could _falsely_ publish a key revocation. If they continue to use their original key on the DNS layer, no names would ever be redeemable again on Handshake. This design requires placing massive trust in the hands of various DNS entities.

4. If godaddy's keys are compromised, we cannot _rely_ on them to publish a proper revocation proof for every individual key they control. They may simply not do it (understandable, since it doesn't really add anything on the DNS layer, and it's also a _massive_ pain to do).

---

So after exploring both of these ideas, I've personally come to the conclusion that:

1. RRSIG timestamps are useless to us.
2. DNSSEC key revocations (that is, signed DNSKEYs with the REVOKE bit set) are useless to us.

## Idea 3: Mass account hack mitigation plus emergency soft-forks

The fact is, we can't expect godaddy to provide revocations for tens of thousands of domains in the case that godaddy _accounts_ get mass hacked. We also can't expect them to produce revocation proofs if ZSKs are compromised.  Furthermore, we can't trust verisign or other entities to not _falsely_ publish a revocation proof in order to hamstring the network (which they, in theory, have the incentive to do).

What we _can_ do is handle what can reliably on chain and then punt the rest of the problems to miners.

I think we should KISS here: assume name claims have a 30 day locktime before redemption. We require all signed TXT records commit to a block hash. We allow _replacement_ of older proofs with a higher block hash. When a proof is replaced on-chain, the 30 day locktime refreshes and restarts. The newly invalidated output is effectively burned from the system (meaning, the coin reward is in a sense "transferred" to the new output -- no inflation has occurred despite there being two outputs with equivalent value).

The new design becomes this:

- Scenario 1 (com's key is compromised): Soft-fork event
- Scenario 2 (godaddy's keys are compromised): Soft-fork event
- Scenario 3 (godaddy's _accounts_ are compromised): Mitigated on-chain

Note that any of these scenarios would be _major news_. Any of us nerds reading hacker news would spot it right away. Furthermore, I suspect _we_ may notice it on chain before anyone else. If it appears that wikipedia has claimed their name on-chain, I would expect HNS users to tweet to them congratulating them, at which point they would respond with something along the lines of "...we didn't do that". By introducing incentives, HNS is effectively becoming the warning system for DNS hacks.

In the case that _keys_ are compromised (scenario 1 & 2), miners have 30 days to reach consensus and deploy an emergency soft-fork to protect the network (note that it is in _everyone's_ interest, including the miners, to deploy this soft-fork). This soft-fork should extend the 30 day locktime by a month or two in order to give us some extra breathing room. Once we have collected all DNSSEC keys which were compromised (easier said than done for scenario 2), they are hardcoded into HSD and whatever other clients are available. The second stage soft-fork would _reject_ the redemption of outputs created by proofs containing any of these keys. The rightful owner can do a replacement proof with the new DNSSEC key(s) and a higher committed block hash. All of this on-chain behavior should look perfectly valid to legacy clients.

The case that _accounts_ are compromised has very different implications: the attacker only has a limited amount of time to create ownership proofs. They will eventually lose access to the account and be unable to create newer proofs. Assuming godaddy/namecheap/etc reverts the hack in a reasonable amount of time (within 30 days), the rightful owner can do a replacement with a higher block hash.

Is it perfect? No. Is it messy? Yes. Is it sufficient to protect this network?  I think so.

## Other Ideas

One idea we discussed was to require a name claimant to put up some coins when claiming a name, perhaps an amount equivalent to the current block reward. If we remember that a hacker has compromised somebody's _godaddy account_ and not their actual wallet, this means that an attacker has to put up _their own coins_ to fund their attack.

If we went that route, there would be considerably more risk for the attacker in trying to grab as many names as possible. I think it would actually change the shape of the attack: instead of going for quantity, they would go for quality, and just try to grab the most high value names. There's benefits to this in that there's much less traffic on-chain when trying to handle the revocations (via whatever mechanism we choose). It's an idea worth thinking about, but I think right now it would be too difficult to implement given our current design (ownership proofs reside in the coinbase instead of their own transaction).

**Comment by pinheadmz** [comment]
@chjj should we close this issue? Looks like the fix has been pushed.

**Comment by pinheadmz** [comment]
Closing due to mainnet launch.
