### ISSUE TITLE
`lockedUnconfirmed` vs `lockedConfirmed` balance inconsistent when recovering from mnemonic

### ISSUE THREAD

**Issue by turbomaze** [handshake-org/hsd#104]
## Background

I was debugging various confusing issues related to a) inconsistent wallet states, b) "forgotten" auctions (sent an open/bid/reveal, but the node couldn't find the auction for the redeem/register), and c) the wallet sending invalid transactions. Haven't dug too deeply into this yet and don't have many concrete details to share about these problems at this stage. Maybe in the next few days. Anyway, I wanted to get to a clean state, so I started from a fresh computer and recovered from the master mnemonic.

## Problem
After recovering on a fresh computer, I compared the output of `hsw-cli account get default` on the problematic node to the freshly created node. Key issue is #8 in the following comprehensive list of differences:

1. The `receiveDepth` on the problematic node was 1 greater than that of the fresh node.
2. The `receiveAddress` was consequently different
3. The problematic node's `.balance.tx` was slightly smaller than that of the fresh node.
4. The problematic node's `.balance.coin` was slightly smaller than that of the fresh node.
5. The problematic node's `.balance.unconfirmed` was much larger than that of the fresh node.
6. The problematic node's `.balance.confirmed` was _greater_ than its unconfirmed balance.
7. The fresh node's unconfirmed and confirmed balances were identical (expected, since it was populated from a `rescan 0`).
8. The problematic node's `.balance.lockedUnconfirmed` and `.balance.lockedConfirmed` were roughly the same, whereas the fresh node's `.balance.lockedUnconfirmed` *was zero* and `.balance.lockedConfirmed` was very similar to the problematic node's `.balance.lockedConfirmed`.

## Details

This node had a lookahead parameter of 1000 to ensure it found every address the full node has used. Other than that, there aren't any relevant changes.

**Comment by bemusementpark** [comment]
What are the impacts? does this cause https://github.com/handshake-org/hsd/issues/378?

**Comment by pinheadmz** [comment]
@turbomaze can we close this? it's very old and I know we have wallet issues but I think we've also gotten better at identifying more specific problems to fix.

**Comment by turbomaze** [comment]
Yeah probably fine to close
