### ISSUE TITLE
P2WSH First Class Citizen?

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#111]
# Overview
Looking through the codebase, I am noticing some inconsistencies regarding pay to script hash

For the script types, there is no mention of a script type `SCRIPTHASH` as seen in bcoin here:
https://github.com/bcoin-org/bcoin/blob/2b2e53d83d4def08d25a2ed5c17c5638c3efa7b7/lib/script/common.js#L447

Handshake includes these script types:
https://github.com/handshake-org/hsd/blob/6aa98af5c3568371b1268300d13a5218bba26925/lib/script/common.js#L448-L453

Based on this code, it leads me to believe that p2sh would be considered `NONSTANDARD` on Handshake
https://github.com/handshake-org/hsd/blob/6aa98af5c3568371b1268300d13a5218bba26925/lib/script/script.js#L1479-L1490

My reference is here in bcoin:
https://github.com/bcoin-org/bcoin/blob/2b2e53d83d4def08d25a2ed5c17c5638c3efa7b7/lib/script/script.js#L1712-L1720

```javascript
    if (this.isScripthash())
      return scriptTypes.SCRIPTHASH;
```

It is possible to create `Address` objects `fromScript`
https://github.com/handshake-org/hsd/blob/6aa98af5c3568371b1268300d13a5218bba26925/lib/primitives/address.js#L212-L215
There is also an `address.isScripthash` method
https://github.com/handshake-org/hsd/blob/6aa98af5c3568371b1268300d13a5218bba26925/lib/primitives/address.js#L351-L353

~~There is no `Script.fromScriptHash`, it was removed here:
https://github.com/handshake-org/hsd/commit/6e0d489aecd471fdd079662cd3db4c4c38dde997#diff-4c95e04aa7e67e17142b5b05b36d4e90L1519~~

# Question

- Why is there no script type `SCRIPTHASH`?

**Comment by chjj** [comment]
There are no output scripts in handshake, only witness programs. For this reason, p2sh doesn't need to be encoded in a script. It's encoded in a witness program instead. The `isScripthash` methods were moved to the `Address` class.
