### ISSUE TITLE
Expose REST API endpoints and websocket events for names

### ISSUE THREAD

**Issue by chjj** [handshake-org/hsd#12]
This includes auction events, etc. Should be useful if someone wants to build a web registrar on top of HSKD.

Currently, only the JSON-rpc interface has been modified to accommodate names. We can do better.

**Comment by pinheadmz** [comment]
Auction endpoints were added in https://github.com/handshake-org/hsd/pull/163
As far as auction events, closing this in favor of https://github.com/handshake-org/hsd/issues/193
