### ISSUE TITLE
Expose Identity Public Key via API

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#141]
# Overview

Right now it is not straight forward to connect to peers on the network because it is not possible to view the p2p identity keys through the API.  A peers address is `pubkey@ip:host`, where the pubkey is a base32 encoded secp256k1 public key. There is no way to query for your own node's pubkey through the HTTP/RPC endpoints. The only way to get this is to watch your logs for this logline:
https://github.com/handshake-org/hsd/blob/af86d4899791601d10212115c80a2f2136fdb004/lib/net/pool.js#L206
or calculate it yourself using the private key at `~/.hsd/key`.

There is also no way to query for your peers' pubkeys. This means that a node operator needs to inspect their `~/.hsd/hosts.json` file to determine usable addresses to share with other node operators.

# Proposal

- Node HTTP `GET /` returns `pool.key`
- Node RPC `getnetworkinfo` returns `key`
- Node RPC `getnetworkinfo` returns `key` field in each `localaddresses` item
- Node RPC `getpeerinfo` returns `addr` that includes the identity key
- Node RPC `getpeerinfo` returns `localaddr` that includes the identity key

**Comment by tynes** [comment]
# Implementation `NetAddress.getKey`

The first change to allow for this functionality would be adding a `getKey` method to the `NetAddress` class. Then the key could be easily retrieved with this getter and properly serialized to the correct format for the usecase.

This could be implemented in `lib/net/netaddress.js` like so:

```javascript
const base32 = require('bs32');

...

  /**
   * Get key
   * @param {String} enc
   * @returns {String|Buffer}
   */

  getKey(enc) {
    if (enc === 'base32')
      return base32.encode(this.key);

    if (enc === 'hex')
      return this.key.toString('hex');

    return this.key;
  }
```

This prevents the need to import `base32` in all the places in the codebase where a `base32` serialized key is required

**Comment by tynes** [comment]
# Implementation `GET /`

https://github.com/handshake-org/hsd/blob/bd1ba3dfca841655ada5ab96e70619112721c049/lib/node/http.js#L121-L135

The code `key: addr.getKey('base32')` could be added between lines 131 and 132.

**Comment by kilpatty** [comment]
I second the need for adding the identity key to the get info response so that it's easier for us to share details with new nodes who want to directly add a peer. 

It mimics the behavior that LN shows in their GetInfo Response here: https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.proto#L1293

Happy to push up a PR for this later today.

**Comment by tynes** [comment]
Here is the function in `hnsd` that prints the identity key - https://github.com/handshake-org/hnsd/blob/master/src/daemon.c#L324
