### ISSUE TITLE
Additional Wallet HTTP Endpoints

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#143]
# Overview

An even higher priority TODO than migrating the node RPCs to HTTP is moving the wallet RPCs to HTTP. In its current form, the wallet can only be safely accessed in a single threaded manner since you need to use the wallet RPC `selectwallet` to select which wallet you are interacting with (Thanks to @Thann for pointing that out). There is also no good way to specify specific accounts. This is important for @mslipper, @turbomaze, @BluSyn and anybody else that is building on top of the wallet. Please suggest any changes or updates based on your usage so far.

# Proposal

Additional Endpoints to be added:

| RPC        | HTTP           | Usage          | WalletClient Method |
| ------------- |:-------------:|:------:|:-----------------:|
| `getnames` |`GET /wallet/:id/names` | Get info on all names the wallet has bid/opened | `getNames`
| `getauctions` |`GET /wallet/:id/names` | Alias for above | `getNames`
| `getnameinfo`   | `GET /wallet/:id/name?name=foo` | Get info on a single bid/open  | `getName`
| `getauctioninfo` | `GET /wallet/:id/auction?name=foo` |  Monitor a single auction once the open period ends | `getAuction`
| `sendopen` | `POST /wallet/:id/open`         | Create an open transaction | `createOpen`
| `sendbid` | `POST /wallet/:id/bid`       | Create a bid transaction | `createBid`
| `getbids` | `GET /wallet/:id/bid?name=foo`       | Get bids for a specific name | `getBid`
| `sendreveal`| `POST /wallet/:id/reveal` | Create a reveal transaction | `createReveal`
| `getreveals` | `GET /wallet/:id/reveal?name=foo` | Get reveal for a specific name | `getReveal`
| `sendredeem` | `POST /wallet/:id/redeem` | Create a redeem transaction | `createRedeem`
| `sendupdate` | `POST /wallet/:id/update` | Create an update transaction | `createUpdate`
| `sendrenewal` | `POST /wallet/:id/renewal` | Create a renew transaction | `createRenew`
| `sendtransfer ` | `POST /wallet/:id/transfer` | Create a transfer transaction | `createTransfer`
| `sendfinalize` | `POST /wallet/:id/finalize` | Create a finalize transaction | `createFinalize`
| `sendcancel` | `POST /wallet/:id/cancel` | Cancel the transfer transaction | `createCancel`
| `sendrevoke` | `POST /wallet/:id/revoke` | Burn the name forever | `createRevoke`
| `importnonce` | `GET /wallet/:id/nonce?name=foo&address=bar&value=100` | Regenerate a bid's nonce | `getNonce`

- Regarding `getnames` and `getauctioninfo`, I've gone back and forth a few times on those endpoints, I thought they might be useful to be overloaded but that could also be a bad idea. Their difference depends on namestate that the client may not know without asking first
- Any endpoints that are used to create transactions can be passed a `sign: false` flag that will return the transaction to the client without signing the transaction. Yay hardware
- The endpoints that do not have corresponding RPCs are to help make certain requests less expensive
- All `createXXX` endpoints work with a specific wallet (based on the URI path) and can be passed an `account: accountId` parameter
- All `createXXX` endpoints can accept standard `createTX` options:
https://github.com/handshake-org/hsd/blob/bd1ba3dfca841655ada5ab96e70619112721c049/lib/wallet/http.js#L417-L432
- `hs-client` would need to be updated. The `WalletClient` would need to be updated with methods and `bin/hsw-cli` would need to be updated with new commands that wrap the new methods

---

Previous Issues mentioning this include https://github.com/handshake-org/hsd/issues/12, https://github.com/handshake-org/hsd/issues/126

**Comment by mslipper** [comment]
We don't make any direct HTTP calls to HSD. Everything is piped through `hs-client`. I'd personally like to be able to pass a `wallet` or `account` argument to every wallet- or account-aware endpoint to prevent having to manually switch them.

**Comment by tynes** [comment]
@mslipper Thanks for taking the time to look at this. I should have made it more explicit - `hs-client` already wraps existing HTTP endpoints, so now I have added the methods that could be added to the `WalletClient` for these HTTP endpoints. Each endpoint that creates a TX can accept an `account` argument, and the `WalletClient` can be configured to be specific to a wallet

```javascript
const wallet = walletClient.wallet('my-wallet-name');
const info = await wallet.getInfo();
```

Or you can just pass the `walletId` along as the first argument

```javascript
const info = await walletClient.getInfo('my-wallet-name');
```

See the implementation of `getInfo` - it just wraps `GET /wallet/${id}`
https://github.com/handshake-org/hs-client/blob/master/lib/wallet.js#L365

**Comment by pinheadmz** [comment]
Great overview!
Would be great to have these as CLI commands in `hsw-cli` as well.

**Comment by turbomaze** [comment]
Thanks a bunch for this! Biggest pain point right now is having to deal with the `selectwallet` call for the rpc endpoints. Doing everything with http would be much safer. `{ sign: false }` would also be much desired! Would make moving names out of cold storage much more convenient.
