### ISSUE TITLE
New TLDs SSL Certs

### ISSUE THREAD

**Issue by jafri** [handshake-org/hsd#149]
How will new TLDs work in current browsers such as chrome/firefox that require certificates for SSL if there is not a root CA?

Namecoin runs a DNS server locally that hydrates dehydrated certificates stored on the blockchain and then injects them into appropriate secure stores.

Another option was DANE-DNSSEC using tlsa records, however there is essentially non-existent support on browsers.

**Comment by chjj** [comment]
> How will new TLDs work in current browsers such as chrome/firefox that require certificates for SSL if there is not a root CA?

I don't understand the question. DNS and SSL are separate things. CAs could only be associated with particular TLDs by way of regulation, not technical limitations. Any entity with a root cert and keypair is free to sign anything they please. If it were any other way, we would be living in a world with only one cert/key for `com.` held by verisign (for example).

> Namecoin runs a DNS server locally that hydrates dehydrated certificates stored on the blockchain and then injects them into appropriate secure stores.

> Another option was DANE-DNSSEC using tlsa records, however there is essentially non-existent support on browsers.

Solutions for this are discussed in great detail in the handshake paper (almost all of which are already implemented in several forms).

**Comment by pinheadmz** [comment]
There have been some community written guides on how to use TLSA/DANE with Handshake:

https://medium.com/@matthewzipkin/building-a-secure-website-on-your-handshake-tld-a8922a950a4f

https://medium.com/@matthewzipkin/using-hns-websites-securely-69959ae02052

https://medium.com/@ca98am79/how-to-view-dane-tlsa-websites-on-handshake-with-firefox-f55eb1dd5be9
