### ISSUE TITLE
Loader/seed nodes appear to be offline

### ISSUE THREAD

**Issue by kilpatty** [handshake-org/hsd#172]
I'm having trouble connecting any new nodes to the loader nodes that are hardcoded as testnet seeds. When I try to scan them using nmap at port 13038 it appears that they all have port 13038 closed. 

I originally thought this may be an issue with the nodes thinking they were not synced due to the long break in block times, and therefore weren't serving up any blocks -> But the network mined a block last night which would have triggered all nodes to think they are synced (HNScan's node showed progress = 1), and still new nodes were not receiving any information from the loader nodes. 

I'm going to try to find the node we use behind HNScan's identity key so that nodes can at least manually add them to their peers until this is fixed.

**Comment by tynes** [comment]
Making progress on https://github.com/handshake-org/hsd/issues/141 would help with this problem, because then it would be a lot easier to get the identity keys of peers, so that we can share node addresses in a p2p fashion more easily

**Comment by kilpatty** [comment]
Closing this as the loaders appear to be back now -> That being said I'd like us to put a process in for seed nodes for main net. I know we've talked about DNS based methods, but I'll reserve that for a different issue.
