### ISSUE TITLE
Brontide: differing length serialization

### ISSUE THREAD

**Issue by kilpatty** [handshake-org/hsd#205]
In my conversion of the brontide file to Rust, I noticed that length is written in two different formats depending on the class used. 

In the Brontide class, the length of the packet is written as a u16 in big endian format seen here - using 2 bytes: https://github.com/handshake-org/hsd/blob/master/lib/net/brontide.js#L424

In the BrontideStream class, the length of the packet is written as a u32 in little endian format seen here - using 4 bytes: https://github.com/handshake-org/hsd/blob/master/lib/net/brontide.js#L557

Is there a reason for this difference? I also noticed we don't even utilize the class Brontide's read or write at all, only BrontideStream. Should we remove that from the file to reduce any confusion?

**Comment by chjj** [comment]
LN uses 16 bit lengths since it's meant to a be a small protocol. All of the brontide test vectors assume 16 bit lengths, so those functions are unused except in testing. I think it's probably important to keep them, just to make sure all of the crypto is executing properly.

**Comment by kilpatty** [comment]
Ah that's my bad on not recognizing that. I converted my rust stuff to allow for packet size to be optionally changed, not sure if anyone would be interested if I converted that over. 

I may make some comments on those write/read functions to clarify that right now they are only used for testing, as well as build a document similar to LND's BOLT 8 testing spec. Will close now though.
