### ISSUE TITLE
On Resolving Alternative DNS Systems

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#208]
There are certain Top Level Domains that are blacklisted by policy. In Bitcoin, policy rules are generally more strict than consensus rules and can be changed by users at runtime. They allow for community consensus to change rules over time based on how the network is evolving. See the [bitcoind](https://github.com/bitcoin/bitcoin/blob/c536dfbcb00fb15963bf5d507b7017c241718bf6/src/policy/policy.cpp) policy file for an example.

For the Top Level Domains that are blacklisted by policy, it is possible to resolve these TLDs if specific client code was written and the community agreed on integrations. It would allow a user to be able to run `hsd` as their DNS server and be able to resolve additional custom Top Level Domains that already exist that are not part of the traditional ICANN system. 

The Top Level Domains that are currently blacklisted by policy are:

```js
const blacklist = new Set([
  'bit', // Namecoin
  'eth', // ENS
  'exit', // Tor
  'gnu', // GNUnet (GNS)
  'i2p', // Invisible Internet Project
  'onion', // Tor
  'tor', // OnioNS
  'zkey' // GNS
]);
```

https://github.com/handshake-org/hsd/blob/master/lib/dns/server.js#L51-L60

The code was written in a way where clients for these TLDs can easily be integrated into the codebase. A client for any of the TLDs in the blacklist could be added here and used instead of doing a lookup in the Urkel Tree.

```js
const data = !blacklist.has(tld)
  ? (await this.lookupName(tld))
  : null;
```
---

Are there any additional TLDs that should be blacklisted by policy?  There is Blockstack's [BNS](https://docs.blockstack.org/core/naming/introduction.html) but I am unclear if they only allow certain TLDs or if they are a complete alternative naming system. A naming service built on Zilliqa recently launched called [ZNS](https://github.com/unstoppabledomains/zns) that uses the `.zil` Top Level Domain and another blockchain project called [Emercoin](https://emercoin.com/en/documentation/blockchain-services/emerdns/emerdns-introduction) supports the TLDs `.coin`, `.emc`, `.lib` and `.bazar`. I do not know how much these services are used in practice.

One concern that I have is without a reproducible build system in place, it could be possible to sneak in alternative lookups. An adversary may be interested in changing the `lookupName` function or any of the potential clients so that it instead reads from a key/value store that they control. The Urkel Tree root can be used to prevent attacks like this for DNS records that are native to the blockchain, but not all of the above TLDs may have authentication schemes.

**Comment by kilpatty** [comment]
It feels as if we should define some standard for the blacklisted domains to be included - which should even apply to the already existing ones. If we don't do this, I worry that we will have ever-increasing creep to new TLDs that people want to reserve. e.g. If I want a TLD before mainnet, what's to stop me from claiming to launch a new domain service on X chain and that we are going to use .X as our TLD, therefore bypassing the bidding process that Handshake sets out to make the TLD playing field more fair and transparent. 

That being said, I'm not sure how we would quality them - age, number of currently existing domains?

**Comment by tynes** [comment]
> I worry that we will have ever-increasing creep to new TLDs that people want to reserve

That is a good point. The current blacklist includes projects that are more mature/well known. I am not sure if I would support adding random projects that do not have a reputation for being useful in some way.  Note that __anybody__ can add their own custom client code in their own node software to resolve however they want. It comes down to what software is ran by the users because this blacklist is enforced by policy alone. A side effect of this discussion is meant to highlight this fact.

**Comment by pinheadmz** [comment]
The names you listed may be blacklisted (basically just ignored) by the DNS server, but as far as names, auctions, and p2p relay policy these names are not blacklisted, they are _reserved_. (As far as I can tell). If you check out

https://raw.githubusercontent.com/handshake-org/hsd/master/lib/covenants/names.json 

You can see the "blacklisted" names are actually reserved:

```
["bit.namecoin.org.", 0],
["ens.fr.", 0],
["eth.ens.domains.", 4, 10200000000000],
["exit.torproject.com.", 0],
... (etc)
```

In these cases (again, AFAICT) the _subdomain_ is the reserved name. It's easy to test:

```
$ hsd-rpc getnameinfo bit
{
  "start": {
    "reserved": true,
    "week": 51,
    "start": 1872
  },
  "info": null
}

$ hsd-rpc getnameinfo namecoin
{
  "start": {
    "reserved": false,
    "week": 4,
    "start": 180
  },
  "info": null
}
```

So if I'm understanding this all correctly, `dns/server.js` is where the external resolvers could go, without any p2p policy/rules changes etc. IN FACT, perhaps the most dope path for these would be `hsd` plugins (with source code signed by the project devs) that users could just install that would specifically handle these domains.

**Comment by pinheadmz** [comment]
Related: #541 -- I think we can make it a lot _easier_ for the blacklist rules in the hsd dns server to be manipulated by user configuration, instead of asking the user to replace their HNS resolver entirely with a different client. Gonna keep this issue open and maybe close along with #541 if we get a good patch for that.

**Comment by pinheadmz** [comment]
Please see https://github.com/pinheadmz/holdmyhand which requires update to hsd (review requested!) https://github.com/handshake-org/hsd/pull/558

**Comment by pinheadmz** [comment]
I'm going to close this now because, as the mathematicians like to say "the solution exists". #558 is merged, and the `holdmyhand` plugin has been released. Users or services interested in applying extra protection can do so in the applicaiton layer (i.e. with a plugin) and so I don't think this is a relevant issue to hsd anymore.
