### ISSUE TITLE
On the Possibilities of the Meta Zone

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#215]
Everybody wants data availability, but its not for free.

Each Handshake name gives 512 bytes of incentivized data availability and anybody can run a full node to help scale database reads. Many users would like to store all sorts of data on chain, but this will bloat the size of the database, and everybody will need to bear that burden since all data is replicated and validated across all full nodes.

That is why there has been discussion of only allowing certain types of DNS records on chain (https://github.com/handshake-org/hsd/issues/125). Users still have control of their root of trust and can run their own DNS infrastructure to scale serving records for domains/subdomains off of their Handshake based Top Level Domain.

Is it possible to expand the amount of space that each Handshake name has without requiring every full node to store it? The idea of a "Meta Zone" could be used to solve this problem, where each Handshake name is also a valid domain under a meta-TLD. I am not quite sure how this would be built, but it sounds fun to think about. The name UTXOs could be 1:1 mapped into the new system.

One way to do it would be to add exceptions to the `lib/covenants/rules.verifyString` function.
https://github.com/handshake-org/hsd/blob/master/lib/covenants/rules.js#L183

```js
    // No unicode characters.
    if (ch & 0xff80)
      return false;
```
You can see that unicode characters are strictly forbidden in domain names. This means that no users will be able to buy names with unicode characters in them. If its possible to build such a system, maybe the meta TLD could be a specific unicode character.

Then people will be able to have more space to make data available, but the burden won't fall on full nodes. It would be another system acting as the authoritative source of that data.

Note: This is pure speculation and not meant to be taken too seriously.

**Comment by pinheadmz** [comment]
I think this concept is basically addressed by the layer-2 protocol Footnote!

https://github.com/kyokan/footnote

Going to close this discussion, the extra data storage you seek for your handshake names will be provided by applications like this ;-)
