### ISSUE TITLE
Testnet seed nodes

### ISSUE THREAD

**Issue by MitchellCash** [handshake-org/hsd#228]
Attempting to connect to any of the seeds in the `README` I am getting `ECONNREFUSED`.

I also note the `README` mentions `testnet3` is running, but I have seen some issue comments on this repo that refer to `testnet4`.

Could I get some clarification on which `testnet` version is currently running and whether there was a new list of known good seed nodes.

I can update the `README` with this new information, unless someone else picks it up.

**Comment by kilpatty** [comment]
Hey @MitchellCash we are currently on testnet4, I believe the readme is just not updated yet. 

The seeds at the moment are down, but we are running a node behind hnscan that you can connect to using this network address:

`ak2hy7feae2o5pfzsdzw3cxkxsu3lxypykcl6iphnup4adf2ply6a@138.68.61.31:13038`

You can add this to your seed file manually, call the add node rpc, or start your node with this as a flag.  Hopefully that helps!

**Comment by MitchellCash** [comment]
Thanks @kilpatty!

I was able to figure that out after posting on Reddit (someone even recommended the hnscan node), I was just concerned for the next "me" that came along and got lost.

It would be good to update the `README` with any updated information - maybe even show the explicit `hsd-cli addnode` command as well 😀

**Comment by pinheadmz** [comment]
closing in favor of https://github.com/handshake-org/hsd/issues/365
