### ISSUE TITLE
"Could not resolve preferred inputs." Error when calling "sendreveal"

### ISSUE THREAD

**Issue by wi-ski** [handshake-org/hsd#231]
### Context
I have a wallet - with two separate accounts, both bidding for the same name - calling sendreveal and passing an account name throws this error `"Could not resolve preferred inputs."`.  I'm totally able to call sendreveal when using only **1** account and calling sendreveal.

This guy: https://github.com/handshake-org/hsd/blob/e1c0281dd9e9bbbd23f5cd832c82ebe3808e9b4f/lib/primitives/mtx.js#L1710

I have no idea what a "preferred input" is in this context. Could I get some guidance here? :heart:  @tynes (we spoke about this over Telegram) cc. @chjj

**Comment by wi-ski** [comment]
After reading the description - I thought I'd reiterate:

a. The wallets has two accounts (loser and winner)
b. Both accounts have placed a bid on a name ("foo")
c. Once the auction has reached the reveal period, calling sendReveal - and passing each account's name as a param - causes the error.

Worth Mentioning:
1. When the wallet only has one account involved in the auction, im able to call sendReveal and pass the account name.
2. Using the sendRevealAll 'works' - eg. it doesnt error.

**Comment by pinheadmz** [comment]
I can confirm this issue with a brief test:

https://gist.github.com/pinheadmz/fc9b4d0fcbb4041ebd8e938f9f52b92d

`Error: Could not resolve preferred inputs.`

I'll go down this rabbit-hole with ya, @wi-ski !

**Comment by pinheadmz** [comment]
@wi-ski got a WIP answer for ya: https://github.com/handshake-org/hsd/pull/233

**Comment by wi-ski** [comment]
Oh heck yea! Thank you so much for taking a look :) Sincerely, you're the best. I just tested your fix and it totally worked :tada:

**Comment by wi-ski** [comment]
I _believe_ Im following :thinking: Ill take a deeper look in the day time, but this feels straight forward.

Again - thank you for the help :)

**Comment by wi-ski** [comment]
Alright - looks like we need the same for `sendupdate`: https://github.com/pinheadmz/hsd/pull/1/files

:point_down: Is that in the right spirit? Tests incoming if so.
