### ISSUE TITLE
'Already sent an open for: <domain>' on expired domain

### ISSUE THREAD

**Issue by rsolari** [handshake-org/hsd#237]
I am trying to re-open an auction on an expired name that I originally opened. I get an error `Already sent an open for: <domain>`  from my fullnode.

My understanding is that we should be able to re-open auctions for expired names. Is that right?

Looks like [txdb#isDoubleOpen](https://github.com/handshake-org/hsd/blob/325747e25a4843c374e37b96fbd161797052953b/lib/wallet/txdb.js#L823) rejects old opens even when the name has returned to the unopened state.

Steps to recreate:
- Open an auction on, for example, `testdomain`.
- Wait for bidding, reveal, and close to expire with no bids.
- No one bid, so no one won the auction. The name is now unopened.
- Try to send an open from `testdomain` from the same fullnode. It errors with `Already sent an open for: testdomain`.

**Comment by pinheadmz** [comment]
Check out this branch: https://github.com/handshake-org/hsd/pull/94

It might solve your issue. Any review / feedback on that PR is appreciated!

**Comment by rsolari** [comment]
Thanks! Looks like that will help.
