### ISSUE TITLE
Master Branch Broken on testnet4

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#239]
Breaking changes were introduced to the master branch. If you would like to connect to testnet4, the last stable commit is cc1ef7ab.

**Comment by jacobhaven** [comment]
Could you create something like a `stable-testnet4` branch or tag (preferably a branch)

**Comment by boymanjor** [comment]
I've created the branch `testnet4-stable` with HEAD https://github.com/handshake-org/hsd/commit/cc1ef7ab8dfcadbcc1b18b934ccf2d2ec1776042.

**Comment by boymanjor** [comment]
Closing this after creating the `testnet4-stable` branch and updating the README on `master`.
