### ISSUE TITLE
Proposal: Commit to airdrop tree roots in genesis block.

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#245]
A funny thing about hsd is that there are a few bits of consensus-critical data in peripheral files. The airdrop tree root and faucet tree root are committed to in `lib/primitives/airdropproof.js`, and the ICANN key-signing keys are committed to in `node_modules/bns/lib/constants.js`. 

I understand the reason these are currently where they are, but it feels like since they are esentially part of the parameter set that defines the hsd blockchain, they should maybe also live in `lib/protocol/consensus.js` and I think they should be also be committed to somewhere in the genesis block.

I've been playing around with airdrop proofs and reserved name claims, and modifying these critical values so I can generate valid proofs in regtest. It made me wonder how possible it would be for an attacker to create a malicious hsd client that snuck in different tree root values and include extra airdrop outputs. Even six months into the chain, an updated client could include a modified tree -- it might hard-fork new nodes syncing for the first time -- but could also silently allow unauthorized airdrop proofs in new blocks, or at least hard-fork the network.

In sort of a related issue, it will be basically impossible for independent auditors to replicate and verify that the 83,000-key airdrop tree is honest. So I think anything we can do to prevent malleability of these data would be at least a confidence-builder.

**Comment by chjj** [comment]
Agreed. Putting it in the coinbase seems sufficient. I think we'll regenerate the trees one more time before mainnet (probably in a few days or so).
