### ISSUE TITLE
Syntax error when running hsd

### ISSUE THREAD

**Issue by kfichter** [handshake-org/hsd#25]
Getting the following syntax error when running `./bin/hsd`:

```
...
[info] (http) Node HTTP server listening on 127.0.0.1 (port=13037).
[info] (ns) Root nameserver listening on port 15349.
Error: syntax error
    at Unbound.setOption (/home/ubuntu/hsd/node_modules/unbound/lib/unbound.js:31:18)
    at UnboundResolver.open (/home/ubuntu/hsd/node_modules/bns/lib/resolver/ub.js:203:13)
    at RecursiveServer.open (/home/ubuntu/hsd/lib/dns/server.js:564:20)
    at FullNode.open (/home/ubuntu/hsd/lib/node/fullnode.js:253:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Seems to be related to `libunbound`, although I have `libunbound-dev` installed.

---

System Information:

```
$ node -v
v10.8.0
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by chjj** [comment]
Hmm, looks like this is the line in question: https://github.com/chjj/bns/blob/master/lib/resolver/ub.js#L203

``` js
this.ub.setOption('trust-anchor-signaling', false);
```

Do you know specifically which version of libunbound is your system using? (`$ unbound -h | grep Version`)

It seems the `trust-anchor-signaling` may have been added/modified/removed in other unbound versions. We turn that option off because it's annoying to see in logs for the root server and it doesn't really add anything.

We should probably add a `trySetOption` call for options that don't really matter all that much.

**Comment by kfichter** [comment]
I originally tried with `1.5.8` but I'm having the same issue with both `1.6.7` and `1.7.3`.

Removing L203 fixes the issue but throws another:
```
[info] (http) Wallet HTTP server listening on 127.0.0.1 (port=13039).
[info] (http) Node HTTP server listening on 127.0.0.1 (port=13037).
[info] (ns) Root nameserver listening on port 15349.
Error: syntax error
    at Unbound.addZone (/home/ubuntu/hsd/node_modules/unbound/lib/unbound.js:65:18)
    at UnboundResolver.open (/home/ubuntu/hsd/node_modules/bns/lib/resolver/ub.js:216:15)
    at RecursiveServer.open (/home/ubuntu/hsd/lib/dns/server.js:564:20)
    at FullNode.open (/home/ubuntu/hsd/lib/node/fullnode.js:253:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I went ahead and deleted the line in question (https://github.com/chjj/bns/blob/master/lib/resolver/ub.js#L217) and things seem to be running.

**Comment by chjj** [comment]
@kfichter I think chjj/bns#c1c2d86244caa81e98626dfd6dcfd530555df924 should fix your issue. Try a fresh `npm install`.

Thanks for investigating this, we can update hnsd to support lower versions of unbound too. I think supporting down to 1.5.0 would probably be reasonable.

Just for our reference, here's the options that are supported in 1.5.0:

- https://github.com/NLnetLabs/unbound/blob/release-1.5.0/util/config_file.c#L583
- https://github.com/NLnetLabs/unbound/blob/release-1.5.0/services/localzone.c#L1216

**Comment by tynes** [comment]
@kfichter Thanks for your bug report! Let us know if the problem was fixed if you have some time

**Comment by kfichter** [comment]
Hi, will check again today and let you know :-)

**Comment by kfichter** [comment]
Just installed `hsd` again and seems to be running well with no errors :+1:
