### ISSUE TITLE
DNSSEC doesn't sign Handshake Onion records

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#264]
Since `Resource.toA` can populate the `Message` (seen as `res` below) with multiple record types, both `A` and `TXT` in the case of of using the built in Onion functionality, it doesn't sign the `TXT` records due to the second argument to `key.signZSK` meaning "commit to this type of record". It is currently hardcoded to `A` records, as seen below. If there are `TXT` records populated in the response (hsd/lib/resource line 472) then they will not be authenticated.

https://github.com/handshake-org/hsd/blob/7c172277476ea2a41501413f4f43a4a0a040b100/lib/dns/resource.js#L1204-L1205

https://github.com/handshake-org/hsd/blob/7c172277476ea2a41501413f4f43a4a0a040b100/lib/dns/resource.js#L454-L473

This is also a problem with `Resource.toAAAA`, as it has similar logic to `Resource.toA`.

**Comment by pinheadmz** [comment]
I'm having trouble grokking this - could you give an example or test with expected and actual behavior?
