### ISSUE TITLE
Use current software to build and run a full node

### ISSUE THREAD

**Issue by 9034725985** [handshake-org/hsd#27]
Expected: npm install works with python3 

Actual: npm install throws an error 

```bash 
[kus@dev hskd]$ npm install

> unbound@0.0.5 install /home/kus/hskd/node_modules/unbound
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/usr/bin/python3" is v3.6.6, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/home/kus/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:501:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/home/kus/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:279:7)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
gyp ERR! System Linux 4.17.9-200.fc28.x86_64
gyp ERR! command "/home/kus/.nvm/versions/node/v10.8.0/bin/node" "/home/kus/.nvm/versions/node/v10.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/kus/hskd/node_modules/unbound
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unbound@0.0.5 (node_modules/unbound):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: unbound@0.0.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 930 packages in 4.602s
found 0 vulnerabilities
```

Python3 is the CURRENT version of python. 

https://github.com/nodejs/node-gyp/issues/746#issuecomment-281911560 

> Our upstream dependency gyp is Python 2 only, and as it's now EoL (Google won't be maintaining it) it's unlikely that it will be updated to support Python 3. 

https://github.com/nodejs/node-gyp/pull/1092 

Do we need gyp? I'll go one step further, do we need node? Can we use something else please?

**Comment by chjj** [comment]
> Do we need gyp?

Unfortunately, yes. I agree, gyp is a disaster. The state of builds on node.js is a headache. Removing native dependencies is a long term goal though. 

Pretty much every native dependency except for unbound and leveldb could use a web assembly backend instead of calling out to C++ ([bcrypto](https://github.com/bcoin-org/bcrypto) for example -- I experimented in the past with an SIMD blake2 wasm impl. which rivaled the speed of the SSE reference implementation when compiled with gcc).

For now, we have to deal with gyp's python2 dependency.

> do we need node?

Yes.
