### ISSUE TITLE
Urkel Tree Variants

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#278]
The Urkel package exposes 3 different tree backends, each with their own set of tradeoffs.

- `optimized`
- `radix`
- `trie`

https://github.com/handshake-org/urkel

The codebase currently uses the `radix` backend.

https://github.com/handshake-org/hsd/blob/daf38ea4dd6ed1b980bd220364777e5744f22fb0/lib/net/packets.js#L16

https://github.com/handshake-org/hsd/blob/17db50874979d6c3fde26916165859713cd0ba81/lib/blockchain/chaindb.js#L14

Differences between `radix` and `optimized` should be investigated, `optimized` sounds like it may be a more efficient implementation of one of the other tree types.

**Comment by chjj** [comment]
`radix` is more DoS resistant, but `optimized` and `trie` (which implement the same construction) are much simpler and are easier to wrap one's head around. I'm still on the fence about which to use. I'm leaning towards the radix tree.

**Comment by tynes** [comment]
Looks like there is general consensus around using `radix`. It has been used in each of the testnets and nobody is pushing to try out the `trie` or `optimized`. Closing.
