### ISSUE TITLE
SLIP-0044 - Register coin type?

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#30]
I think it would be useful to have a registered coin type for `hns` to speed
up community adoption. I believe that all that needs to happen is a concensus
around a specific number and a pull request with that information submitted
to the repo below:

https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by boymanjor** [comment]
I opened a PR to reserve the HNS mainnet coin type (5353) here: https://github.com/satoshilabs/slips/pull/381

Closing this now.
