### ISSUE TITLE
Light Client Certificate Authority

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#300]
Inspired by the work done by GNU Naming System, I believe it is possible to create a service that can effectively sign TLS Certificates purely based on the Handshake network. 

A new type of light client is a decentralized Certificate Authority. It has a hot key, runs in a SOCKS5 proxy and browsers are configured to use it. The machines with browsers must install the CA onto their local machine, so that signatures from it are considered valid. This is not ideal, but we just need to keep the hot key very safe. This means we do not need to convince the browser developers to add custom things to work with Handshake.

For any request going to a Handshake based domain, the light client can request a proof over the p2p network using the `getproof` message. The light client will sign a TLS certificate for the website iff the following conditions are met:

- The namestate proof is valid
- The namestate data contains:
  - `TLSA` record
- The domain returns a TLS cert during the handshake which:
  - Matches the cert in the `TLSA` record
  - Is self signed
  - Has a valid signature

The light client can strip the signature off of the TLS certificate and replace it with a signature of its own. The browser will be able to validate the signature against a CA installed on its machine, so it will be able to display the green checkbox and use TLS.

While the need to install a custom CA isn't ideal, I think that there may be a way to improve on its downsides. Maybe the CA could be rolled over regularly? Maybe the CA uses distributed key generation and its all multiparty ecdsa? (Adds a lot of complexity, but seemingly novel)

There also may be something deep in the [x.509 RFC](https://tools.ietf.org/html/rfc5280) that is helpful for our usecase.

**Comment by pinheadmz** [comment]
https://github.com/buffrr/letsdane

https://impervious.com/fingertip.html

Closing! WE LOVE YOU MARK CALL ME YOU ARE VERY HANDSOME
