### ISSUE TITLE
Setup instructions broken?

### ISSUE THREAD

**Issue by verdverm** [handshake-org/hsd#348]
I just cloned and followed the instructions, however it does not seem to be doing what I expected.

I noticed that the files under `bin` did not update, so I moved the folder, reran the `npm install --production` command, and nothing was created, nor a `bin` folder. The Dockerfile has the same issue.

How does one build and run this correctly today?

**Comment by pinheadmz** [comment]
NodeJS packages don't compile at all, and the contents of the bin folder won't change. You should see a new directory `node_modules` containing all the dependencies. Once installation is complete you can run `bin/hsd` to start a full node on testnet.

**Comment by pinheadmz** [comment]
@verdverm has this been resolved?

**Comment by verdverm** [comment]
@pinheadmz was never really an issue, my lack of familiarity with the bin dir patter used here.
