### ISSUE TITLE
Unclear Windows Instructions

### ISSUE THREAD

**Issue by AdamSC1-ddg** [handshake-org/hsd#354]
Following the guide here: https://handshake-org.github.io/guides/win-install.html

Has a few gaps/issues.

**1. Root Package:**
> Go thru and edit package.json in root hsd/ folder to use file: of the above.

Unclear. The default package.json only contains bcrypto, should we be adding just `"bcrypto": "file:./bcrypto",` or a similar line for each of them?

**2. Root Binding.gyp**
>Edit binding.gyp: `"<!(bash -c \"python -c \"from __future__ import print_function; import sys; print(sys.byteorder)\"\")",`

There is no binding.gyp in the root folder, so I assume we are creating one and placing only this in it?

**3. Other Binding.gyp files:**

It says to do the same for other binding.gyp files - those do exist and have content. Are we replacing the entire content of the file or appending this to it?

**4. No Chacha20 Folder:**

Instructions then say to:

`cd bcrypto`
`cd src`
`cd chacha20`

There is no chacha20 folder within SRC. There are only chacha20.cc and chacha20.h files as can be seen in the repo: https://github.com/bcoin-org/bcrypto/tree/master/src

There is a chacha20.c under /src/torsion/src/chacha20.c and a chacha20.h located at /src/torsion/include/torsion/chacha20.h

**Comment by pinheadmz** [comment]
Please ignore that document and try the install guide inside the repo:

https://github.com/handshake-org/hsd#install

If you have any hints or corrections for windows installation, we'd greatly appreciate a PR to https://github.com/handshake-org/handshake-org.github.io

I think the current docs on that site are out of date.

**Comment by tuxcanfly** [comment]
Seconded @pinheadmz suggestions. I'd also suggest using `--no-optional` flag as I was unable to build `unbound` which was a dep of `bns` because of missing header file `libunbound.h`. So, to put it simply, you need to do `npm install --no-optional --production` and it should just work (tm).

**Comment by pinheadmz** [comment]
I believe this was closed by https://github.com/handshake-org/handshake-org.github.io/pull/48 removing the outdated guide and just redirecting to the hsd README.

More details on windows installation were documented by a community member here: https://www.reddit.com/r/handshake/comments/l5nkpb/how_to_install_hsd_on_win10_and_bigsur/
