### ISSUE TITLE
Remote wallet: several calls send buffers instead of strings to HTTP endpoints

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#357]
In bcoin, hashes are still reversed, and so the wallet client translates the hashes before sending a string to the full node's http endpoint:

https://github.com/bcoin-org/bcoin/blob/8851582be817da7d6b6a1cfa6791b4baf3b8058f/lib/wallet/client.js#L74-L79

```js
  async rescan(start) {
    if (Buffer.isBuffer(start))
      start = util.revHex(start);


    return super.rescan(start);
  }
```

This util function doesn't just reverse the hash, it stringifies it as well.

In hsd, the util is gone completely:

https://github.com/handshake-org/hsd/blob/1c2d1036b262ecb767e71a73cd91ef11c940b230/lib/wallet/client.js#L76-L78

This means remote wallet servers try sending a raw buffer to the full node, which throws an error in `hs-client` here:

https://github.com/handshake-org/hs-client/blob/c5a86ae9b21797d6d50f67dacea6436f3cda5b79/lib/node.js#L308-L322

```js
  /**
   * Rescan for any missed transactions.
   * @param {Number|Hash} start - Start block.
   * @returns {Promise}
   */


  rescan(start) {
    if (start == null)
      start = 0;


    assert(typeof start === 'number' || typeof start === 'string');


    return this.call('rescan', start);
  }
}
```

I can write a patch for this soon but wanted to open an issue first, wanna make sure I catch all these.

**Comment by pinheadmz** [comment]
Ok actually I think this was probably intended to stay as buffers and the type check in hs-client is what needs to come out

**Comment by boymanjor** [comment]
@pinheadmz I followed the code path down to here[1] and agree that we should update `hs-client` to expect a `Number` or `Buffer`.

[1]: https://github.com/handshake-org/hsd/blob/1c2d1036b262ecb767e71a73cd91ef11c940b230/lib/blockchain/chaindb.js#L396

**Comment by boymanjor** [comment]
> expect a `Number` or `Buffer`.

@pinheadmz on second thought, all the other API functions expect a `Number` or `String` when referencing a block. Perhaps we should stay consistent and generate the `Buffer` internally?

**Comment by boymanjor** [comment]
@pinheadmz moving this discussion to your PR.
