### ISSUE TITLE
Issues using DNS seeds to bootstrap to the network

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#359]
I may have executed this wrong, in which case we need some docs, or there might be 2 distinct bugs here. The goal was to use a DNS seeder (running `hs-seeder`) to discover peers and bootstrap to the network.

First try:
```
$  hsd --prefix=~/.hsd/dnsseed --seeds=seed.easyhandshake.com
...
[warning] (net) Could not find enough peers.
[warning] (net) Hitting DNS seeds...
[info] (hostlist) Resolving host: seed.easyhandshake.com.
AssertionError [ERR_ASSERTION]: Assertion failed.
    at HostList.add (/Users/matthewzipkin/Desktop/work/hsd/lib/net/hostlist.js:455:5)
    at HostList.populateSeed (/Users/matthewzipkin/Desktop/work/hsd/lib/net/hostlist.js:1050:12)
    at async Promise.all (index 0)
    at async Pool.discoverSeeds (/Users/matthewzipkin/Desktop/work/hsd/lib/net/pool.js:589:7)
    at async Pool._connect (/Users/matthewzipkin/Desktop/work/hsd/lib/net/pool.js:345:5)
    at async Pool.connect (/Users/matthewzipkin/Desktop/work/hsd/lib/net/pool.js:323:14)
    at async /Users/matthewzipkin/Desktop/work/hsd/bin/node:69:3

```

That error is due to a missing port number:

https://github.com/handshake-org/hsd/blob/1c2d1036b262ecb767e71a73cd91ef11c940b230/lib/net/hostlist.js#L454-L455

So I tried adding a port number:

```
$ hsd --prefix=~/.hsd/dnsseed --seeds=seed.easyhandshake.com:53
...
[warning] (net) Could not find enough peers.
[warning] (net) Hitting DNS seeds...
[info] (hostlist) Resolving host: seed.easyhandshake.com.
[info] (net) Resolved 66 hosts from DNS seeds.
[debug] (net) Connecting to 96.250.207.28:53.
[info] (net) Adding loader peer (96.250.207.28:53).
[debug] (net) Connecting to 211.41.246.66:53.
[debug] (net) Connecting to [2601:341:c180:3a80:182e:dea3:a267:bb1e]:53.
[debug] (net) Connecting to 171.6.236.219:53.
[debug] (net) Connecting to 3.17.33.134:53.
[debug] (net) Connecting to [2604:2000:1403:459c:ca9:15d6:3acb:80be]:53.
[debug] (net) Connecting to [2001:0:2877:7aa:28af:57f2:4ad3:c359]:53.
[debug] (net) Connecting to [2a02:a31a:a146:c80:4:4faa:73cc:147b]:53.
[debug] (net) Error: Socket Error: EHOSTUNREACH 
[debug] (net) Connecting to [2a01:4b00:8069:6400:8f9:f6b7:bcb8:ebab]:53.
[debug] (net) Connecting to 95.165.154.226:53.
[debug] (net) Connecting to 64.203.198.140:53.
[debug] (net) Connecting to [2601:901:4380:1140:1063:17fe:4d37:3baa]:53.
[debug] (net) Error: Socket Error: EHOSTUNREACH ([2a01:4b00:8069:6400:8f9:f6b7:bcb8:ebab]:53)
...
```

Looks like it successfully retrieved the A/AAAA records from the seed node (can confirm on my server logs) but it's trying to connect to all the peers on port `53`!

ping @stp-ip

**Comment by stp-ip** [comment]
Copying over from the discussion:
I guess it stems from the fact that their is no clear separation from DNS seeder seed and DNS seed aka node that is only given by domain.
So it needs the port to connect to, but will first resolve all IPs and use all responses as peers then use the port given to connect as if it were one or multiple nodes.
So no special code on the DNS seeder side in the client.
So defaulting to the default handshake port should resolve the undefined port and overwriting it with a specific one should be fine for the case, where someone specifically wants a dns seed/peer.
