### ISSUE TITLE
Stratum

### ISSUE THREAD

**Issue by neal-zhu** [handshake-org/hsd#368]
Hi there, we are planning to develop a pool of hsd. Are there any documents on stratum protocol? 
Thanks a lot

**Comment by pinheadmz** [comment]
There is no specified stratum protocol for Handshake and from reports I've been getting, each mining pool is implementing it differently (which seems like a very stratum thing to do ☹️ )

You might find what you need in these community-managed repos:

https://github.com/HandshakeAlliance/hstratum

https://github.com/HandyMiner/HandyMiner-CLI

The developers also have an open-source miner, but it does not yet support stratum:

https://github.com/handshake-org/hs-miner

**Comment by EthanHee** [comment]
@neal-zhu  hi,is your pool running now?  I get some problems on HNS pool  too.  hoping for some guides.

**Comment by ruyichang** [comment]
I've found some documentation of hns stratum protocol

**Comment by ruyichang** [comment]
> There is no specified stratum protocol for Handshake and from reports I've been getting, each mining pool is implementing it differently (which seems like a very stratum thing to do ☹️ )
> 
> You might find what you need in these community-managed repos:
> 
> https://github.com/HandshakeAlliance/hstratum
> 
> https://github.com/HandyMiner/HandyMiner-CLI
> 
> The developers also have an open-source miner, but it does not yet support stratum:
> 
> https://github.com/handshake-org/hs-miner

---
Can't open  https://github.com/HandshakeAlliance/hstratum

**Comment by smcki012** [comment]
You can still find hstratum here: https://github.com/HandyMiner/hstratum

We will be working to add proper mask hash support for that stratum as well in the near future.

**Comment by pinheadmz** [comment]
@ruyichang @smcki012 After a brief chat with @kilpatty, the original repo is back open (public) at https://github.com/HandshakeAlliance/hstratum

however I discovered it is quite out of date, I wrote a quick patch but haven't tested it completely: https://github.com/HandshakeAlliance/hstratum/pull/14

Would appreciate review! We just needed to bump the crypto library
