### ISSUE TITLE
hsw to hsd, "invalid magic value"

### ISSUE THREAD

**Issue by tedder** [handshake-org/hsd#369]
I have hsd sitting on one machine, and trying to talk to it from hsw on another. I know the hsd port is open on 12038 (telnet, nmap). However, when hsw tries to connect, hsd rejects it every time:

```
[D:2020-02-13T22:25:02Z] (peer) Sending reject packet to peer (HSWIP:36270).
[D:2020-02-13T22:25:02Z] (net) Error: Invalid magic value: 3231aaaa. (HSWIP:36270)
[D:2020-02-13T22:25:02Z] (peer) Rejecting packet from HSWIP:36270: code=malformed reason=error parsing message.
[D:2020-02-13T22:25:02Z] (peer) Sending reject packet to peer (HSWIP:36270).
[D:2020-02-13T22:25:02Z] (net) Error: Invalid magic value: 7267aaaa. (HSWIP:36270)
[D:2020-02-13T22:25:02Z] (peer) Rejecting packet from HSWIP:36270: code=malformed reason=error parsing message.
```

I wondered if it is a mismatch of `api-key`, in hsd.conf I have this:
```
api-key: b15xxx
```
and in hsw.conf on the second machine I have this:
```
node-api-key: b15xxx
```

By monkeypatching lib/net/parser.js on the HSD machine I can see that it is expecting a constant value, but as the log above (from hsw) shows, it seems to pass a different value on each connection attempt.

Thanks.

**Comment by pinheadmz** [comment]
12038 is the p2p port. hsw needs to connect to the full node on that full nodes rpc port, which for mainnet is 12037:

https://hsd-dev.org/api-docs/#configuring-clients

**Comment by tedder** [comment]
Aha, that did it. I thought the port number was wrong because it wasn't listening. I needed to open it on the hsd side:
```
http-host: 0.0.0.0
```

On the hsw side I'm seeing "assertion error" in the logs after the connection, though there's no info on it. Just FYI. (it isn't #370, which gave a trace)
```
[info] (wallet) Resyncing from server...
[info] (wallet) Sending filter to server (5.1418256759643555mb).
[info] (wallet) Syncing state from height 1962.
[info] (wallet) Rolled back to same height (1962).
[info] (wallet) WalletDB is scanning 1 blocks.
[error] (node) Assertion failed.
```

**Comment by pinheadmz** [comment]
Are you running the latest from master branch? Might have just been fixed: https://github.com/handshake-org/hsd/pull/358

**Comment by tedder** [comment]
Yeah, today's master, latest commit is 6deef58c13f77e98b258064d93521cb2c0243ff1.

**Comment by pinheadmz** [comment]
Hm what about hs-client? Could be this bug:

https://github.com/handshake-org/hs-client/pull/21

this isn't on npm yet, will have to be installed from git

**Comment by tedder** [comment]
Aha, yep, the version hsd pulled from npm didn't have that. No more error now.

**Comment by pinheadmz** [comment]
Phew! Thanks for running the bleeding edge of the project!

**Comment by pinheadmz** [comment]
@chjj may need to bump versions and push to npm

**Comment by chjj** [comment]
@pinheadmz @tedder, hsd was never updated in npm because the installation was meant to be done from the [tarball]. This forces people to use a more secure method of installation (both git and signed tarballs are more secure than npm imo).

I'll update npm to ease people's confusion for now, but I think in the future we should disable the npm package to force installation from the tarball or git.

[tarball]: https://handshake.org/download

**Comment by tedder** [comment]
So [this install section](https://github.com/handshake-org/hsd#install) should point to the tarball.

**Comment by pinheadmz** [comment]
hs-client links have been added to `bin` and instructions added to README
