### ISSUE TITLE
hsw, cannot specify `node-port`, assertion error (and likely fix)

### ISSUE THREAD

**Issue by tedder** [handshake-org/hsd#370]
Whenever I specify a `node-port` in `hsw.conf`, it dies with an assertion error:
```
/path/hsd/node_modules/bsert/lib/assert.js:85
    throw new AssertionError({
    ^

AssertionError [ERR_ASSERTION]: Assertion failed.
    at ClientOptions.fromOptions (/path/hsd/node_modules/bcurl/lib/client.js:372:7)
    at new ClientOptions (/path/hsd/node_modules/bcurl/lib/client.js:350:12)
```

It isn't every helpful, but it was enough for me to debug client.js. I determined that `options.port` [is a string inside of bcurl](https://github.com/bcoin-org/bcurl/blob/v0.1.6/lib/client.js#L370), so this assertion fails:
```
      assert((options.port & 0xffff) === options.port);
```

I monkeypatched that section like this, and it works.
```
      var intport = parseInt(options.port);
      assert((intport & 0xffff) === intport);
      assert(intport !== 0);
      this.port = intport;
```

[So, the "read config" section needs to be modified](https://github.com/handshake-org/hsd/blob/57b5b491699d5438c53ddaeacd8a0e0122306853/lib/wallet/node.js#L38) to make it something other than a string. Probably [uint like http-port](https://github.com/handshake-org/hsd/blob/57b5b491699d5438c53ddaeacd8a0e0122306853/lib/wallet/node.js#L68)?

**Comment by pinheadmz** [comment]
I think you're right about this -- do you have time to make a PR in `wallet/node.js`?

**Comment by pinheadmz** [comment]
This was already patched in bcoin: https://github.com/bcoin-org/bcoin/pull/506/files
