### ISSUE TITLE
can the (net) logging be reduced?

### ISSUE THREAD

**Issue by tedder** [handshake-org/hsd#371]
my `hsd` is full of connections to peers. Note they aren't all debug level, but most are:
```
[debug] (net) Error: Socket Error: ENETUNREACH ([SOMEIP]:12038)
[debug] (net) Connecting to SOMEIP:12038.
[info] (net) Connected to SOMEIP:12038.
[debug] (net) Error: Socket hangup. (SOMEIP:12038)
[debug] (net) Connecting to SOMEIP:12038.
[debug] (net) Error: Connection timed out. (SOMEIP:12038)
[debug] (net) Connecting to [SOMEIP]:12038.
[debug] (net) Error: Socket Error: ENETUNREACH ([SOMEIP]:12038)
[debug] (net) Connecting to SOMEIP:12038.
[debug] (net) Error: Socket Error: ENETUNREACH (SOMEIP:12038)
[debug] (net) Connecting to SOMEIP:12038.
[debug] (net) Error: Connection timed out. (SOMEIP:12038)
[debug] (net) Connecting to SOMEIP:12038.
[debug] (net) Error: Connection timed out. (SOMEIP:12038)
```

(not the scrubbed IPs, above, aren't all the same. Just trying to preserve a little bit of privacy)

Aside from changing the overall log level, is there a way to tell (net) to be quieter, since it's safe to assume many peers will fail? Through an excessive amount of work I found that 95% of the messages come from [peer.on(error)](https://github.com/handshake-org/hsd/blob/master/lib/net/pool.js#L1245) and [createOutbound](https://github.com/handshake-org/hsd/blob/master/lib/net/pool.js#L1184). There are a few others, like ["Connected"](https://github.com/handshake-org/hsd/blob/master/lib/net/pool.js#L1401), but those first two really improved my quality of life.

(okay, done creating issues for now)

**Comment by pinheadmz** [comment]
once your maxOutbound is full (8 peers by default) this will stop. 

You might find the `pool` settings here useful if you're trying a special configuration:

https://hsd-dev.org/guides/config.html

You can, for example, set `nodes=` and `max-outbound=` to prevent hsd from trying to connect to other peers.

**Comment by tedder** [comment]
I seem to have all my peers, yet it's still trying, a few hours into the process:
```
[info] (net) Received 267 addrs (hosts=275, peers=8) (165.22.151.242:12038).
```

**Comment by pinheadmz** [comment]
receiving addr messages is normal, we want peers to gossip available nodes to each other.

`hsd-cli info` should show you how many outbound peers you have. If that says `8` and you haven't set any special configurations, I would expect the pool module to stop attempting more outbound connections, and the log messages in your first post would cease.

**Comment by chjj** [comment]
The `--log-level` option is the solution here. Try `--log-level=info`.
