### ISSUE TITLE
"Error: Not enough funds" while the wallet does have enough balance

### ISSUE THREAD

**Issue by losfair** [handshake-org/hsd#377]
I'm trying to send some funds to another address but got a "Not enough funds" error:

```
$ hsw-rpc sendtoaddress (target-address) 1
Not enough funds. (available=0.0, required=1.0074)
```

However `hsw-rpc getbalance` reports the wallet to have enough balance, and the balance is confirmed.

I also tried other methods of sending transactions (`hsw-cli send` and cURL) but none of them worked. Am I missing something here?

**Comment by pinheadmz** [comment]
If you are trying to spend a recently mined airdrop proof you must wait 100 blocks for the coin to mature.

**Comment by losfair** [comment]
Thanks!
