### ISSUE TITLE
Access to remote node refused

### ISSUE THREAD

**Issue by fabioDMFerreira** [handshake-org/hsd#379]
The access to a remote handshake node from my localhost is refused. Even after enabling cors and disabling authentication (just for test purposes).

This is the command executed to run handshake node.
```
./bin/hsd --cors --no-auth
```

This is the code to access handshake node.
```
const { NodeClient } = require('hs-client');
const { Network } = require('hsd');
const network = Network.get('main');

const clientOptions = {
  host: 'xxx',
  network: network.type,
  port: network.rpcPort,
  apiKey: 'xxx'
}

const client = new NodeClient(clientOptions);

(async () => {
  let data;
  try {
    await client.open();
    data = await client.execute('getnameinfo', ['eth'])
  } catch (e) {
    console.log("Error trying to call remote method: ", e)
  }

  console.log(data);
})()
```

This is the error I get.
```
Error trying to call remote method:  { Error: connect ECONNREFUSED XX.XX.XX.XX:12037
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '104.248.0.96',
  port: 12037 }
```

I already checked firewall isn't blocking requests.

Is there some parameter missing while initializing the node?

**Comment by pinheadmz** [comment]
Yes. You need to set `http-host: 0.0.0.0` to expose the API to the internet. 

DO NOT DO THIS without enforcing SSL setting a string api key

**Comment by pinheadmz** [comment]
More config options here:

https://hsd-dev.org/guides/config.html

**Comment by fabioDMFerreira** [comment]
Works perfectly! Thanks @pinheadmz
