### ISSUE TITLE
mkwallet command is not present when hsw-cli is called with no command

### ISSUE THREAD

**Issue by bemusementpark** [handshake-org/hsd#383]
Why isn't `mkwallet` documented when `hsw-cli` is called with no command?

Are there other commands that are not documented?

in [wallet.md](https://github.com/handshake-org/handshake-org.github.io/blob/master/src/guides/wallet.md) it says that:

> Calling the CLI without any arguments $ hsw-cli will output the list of supported commands

```
$ hsw-cli mkwallet <name-of-new-wallet> --mnemonic=<mnemonic-phrase> --passphrase=<passphrase>
```

but mkwallet isn't present when I call `hsw-cli`. Perhaps other commands are undocumented.

```
hsw-cli
  $ listen: Listen for events.
  $ get: View wallet.
  $ master: View wallet master key.
  $ shared add [xpubkey]: Add key to wallet.
  $ shared remove [xpubkey]: Remove key from wallet.
  $ balance: Get wallet balance.
  $ history: View TX history.
  $ pending: View pending TXs.
  $ coins: View wallet coins.
  $ account list: List account names.
  $ account create [account-name]: Create account.
  $ account get [account-name]: Get account details.
  $ address: Derive new address.
  $ change: Derive new change address.
  $ retoken: Create new api key.
  $ send [address] [value]: Send transaction.
  $ mktx [address] [value]: Create transaction.
  $ sign [tx-hex]: Sign transaction.
  $ zap [age?]: Zap pending wallet TXs.
  $ abandon [hash]: Abandon a transaction.
  $ tx [hash]: View transaction details.
  $ blocks: List wallet blocks.
  $ block [height]: View wallet block.
  $ view [tx-hex]: Parse and view transaction.
  $ import [wif|hex]: Import private or public key.
  $ watch [address]: Import an address.
  $ key [address]: Get wallet key by address.
  $ dump [address]: Get wallet key WIF by address.
  $ lock: Lock wallet.
  $ unlock [passphrase] [timeout?]: Unlock wallet.
  $ resend: Resend pending transactions.
  $ rescan [height]: Rescan for transactions.
```

**Comment by boymanjor** [comment]
Thanks for the issue! Technically, this should be opened [here](https://github.com/handshake-org/hs-client/issues).

Re: the issue - currently, the `mkwallet` command is implemented as an admin command. Running `$ hsw-cli admin` should list the admin commands. However,`mkwallet` is incorrectly listed as `wallet create` on v0.0.8. This was fixed [here](https://github.com/handshake-org/hs-client/commit/64f28c1ae7b3956d8e7cbe90d45dd152d17952cd).

Looking at the wallet http API, I don't believe wallet creation requires admin access. I'm going to close this issue for now, but perhaps open a new issue on `hs-client` regarding `mkwallet` requiring admin access.
