### ISSUE TITLE
Can't sendreveal an auction containing only numbers

### ISSUE THREAD

**Issue by bemusementpark** [handshake-org/hsd#384]
```
hsw-rpc sendreveal "7"
Param #0 must be a string.
```

**Comment by pinheadmz** [comment]
This may not be possible with CLI due to how bash works.

**Comment by mslipper** [comment]
You have to encase the name in single quotes follow by double quotes: `hsw-rpc sendreveal '"7"'`.

**Comment by pinheadmz** [comment]
Thank you @mslipper !
