### ISSUE TITLE
how to run 

### ISSUE THREAD

**Issue by gaoyang1120** [handshake-org/hsd#386]
root@iZ6wefu86owt8f9mdb1ldgZ:~/hns/hsd# ./bin/hsd
/root/hns/hsd/node_modules/loady/lib/loady.js:121
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 - /root/hns/hsd/node_modules/bdb/build/leveldown.node
 - /root/hns/hsd/node_modules/bdb/build/Debug/leveldown.node
 - /root/hns/hsd/node_modules/bdb/build/Release/leveldown.node
 - /root/hns/hsd/node_modules/bdb/out/Debug/leveldown.node
 - /root/hns/hsd/node_modules/bdb/Debug/leveldown.node
 - /root/hns/hsd/node_modules/bdb/out/Release/leveldown.node
 - /root/hns/hsd/node_modules/bdb/Release/leveldown.node
 - /root/hns/hsd/node_modules/bdb/build/default/leveldown.node
 - /root/hns/hsd/node_modules/bdb/compiled/12.16.1/linux/x64/leveldown.node
 - /root/hns/hsd/node_modules/bdb/addon-build/release/install-root/leveldown.node
 - /root/hns/hsd/node_modules/bdb/addon-build/debug/install-root/leveldown.node
 - /root/hns/hsd/node_modules/bdb/addon-build/default/install-root/leveldown.node
 - /root/hns/hsd/node_modules/bdb/lib/binding/node-v72-linux-x64/leveldown.node
    at bindings (/root/hns/hsd/node_modules/loady/lib/loady.js:116:15)
    at Object.<anonymous> (/root/hns/hsd/node_modules/bdb/lib/level.js:9:33)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/root/hns/hsd/node_modules/bdb/lib/bdb.js:13:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30) {
  code: 'ERR_BINDINGS_NOT_FOUND',
  tries: [
    '/root/hns/hsd/node_modules/bdb/build/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/build/Debug/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/build/Release/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/out/Debug/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/Debug/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/out/Release/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/Release/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/build/default/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/compiled/12.16.1/linux/x64/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/addon-build/release/install-root/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/addon-build/debug/install-root/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/addon-build/default/install-root/leveldown.node',
    '/root/hns/hsd/node_modules/bdb/lib/binding/node-v72-linux-x64/leveldown.node'
  ]
}

**Comment by pinheadmz** [comment]
This is an installation issue. Please double check you have met the requirements: https://github.com/handshake-org/hsd#install

**Comment by tynes** [comment]
@gaoyang1120 Please share which version of node.js and npm you are using. I find node.js version 10 to be the most reliable when running `hsd`.
