### ISSUE TITLE
npm install fail 

### ISSUE THREAD

**Issue by rocqina** [handshake-org/hsd#389]
os：centos8

[root@iZj6cgdlmms5oiah1iqmjsZ hsd-2.1.2]# node -v
v12.16.1
[root@iZj6cgdlmms5oiah1iqmjsZ hsd-2.1.2]# npm -v
6.13.4
[root@iZj6cgdlmms5oiah1iqmjsZ hsd-2.1.2]# gcc -v
gcc version 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC) 

[root@iZj6cgdlmms5oiah1iqmjsZ hsd-2.1.2]# npm install --production

> bcrypto@5.0.4 install /work/hsd-2.1.2/node_modules/bcrypto
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/work/hsd-2.1.2/node_modules/bcrypto/build'
gyp ERR! System Linux 3.10.0-957.21.3.el7.x86_64
gyp ERR! command "/root/gp/nodejs/nodejs/bin/node" "/root/gp/nodejs/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /work/hsd-2.1.2/node_modules/bcrypto
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypto@5.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypto@5.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-11T09_29_48_797Z-debug.log

**Comment by rocqina** [comment]
node-gyp -v
v6.1.0

**Comment by pinheadmz** [comment]
This looks like an issue with write permissions. You can try again without the `--production` flag. But this is an issue with access permissions on your OS, not with hsd.

**Comment by rocqina** [comment]
The dir node_modules is generated by npm install. why there is permission denied. I do not think this is my os issue. I change the path of hsd to /work/hsd-2.1.2, and the same issue.

**Comment by rocqina** [comment]
[root@iZj6cgdlmms5oiah1iqmjsZ hsd-2.1.2]# npm install

> bcrypto@5.0.4 install /work/hsd-2.1.2/node_modules/bcrypto
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/work/hsd-2.1.2/node_modules/bcrypto/build'
gyp ERR! System Linux 3.10.0-957.21.3.el7.x86_64
gyp ERR! command "/work/nodejs/bin/node" "/work/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /work/hsd-2.1.2/node_modules/bcrypto
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypto@5.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypto@5.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-12T01_30_38_446Z-debug.log
[root@iZj6cgdlmms5oiah1iqmjsZ hsd-2.1.2]#

**Comment by pinheadmz** [comment]
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/work/hsd-2.1.2/node_modules/bcrypto/build'

This is not an issue with hsd or bcrypto. I haven't tried installing nodejs modules on centos myself yet, I'll try to reproduce.

Or you could look through these links:

https://duckduckgo.com/?q=permission+denied+centos+npm&ia=web

**Comment by tynes** [comment]
> I do not think this is my os issue.

This definitely looks like an operating system issue. Make sure that your `$USER` has the correct permissions.

**Comment by codaelux** [comment]
in case anyone is having this error you need to run `sudo apt install build-essential`
