### ISSUE TITLE
Reselling Handshake TLD?

### ISSUE THREAD

**Issue by truell20** [handshake-org/hsd#391]
What is the best way to sell someone the rights to control a Handshake TLD? Is this supported by Handshake RPC calls?

**Comment by pinheadmz** [comment]
You can transfer a name to a new address. See the api docs for how to transfer. A name is not completely transferred until the FINALIZE is sent, a minimum of two days after TRANSFER. 

https://hsd-dev.org/api-docs

**Comment by truell20** [comment]
Gotcha thanks
