### ISSUE TITLE
"listtransactions" sometimes gets wrong amouts 

### ISSUE THREAD

**Issue by JackieyQi** [handshake-org/hsd#395]
I find the two questions about the rpc calls "listtransactions".
One is the wrong "amount" occured when multi reveives that created by a same wallet within the same transaction. 

Steps to reproduce:

1. Create three address by the same account and wallet.
2. Send transaction to the addresses above, these receives need within the same transaction and same txid.
3. Curl the "listtransactions" with the wallet. And only one last transaction with the three receives total amount, not three with their each amount.

Another is the amount always be 0 if send and receive both are from the same wallet. And the param specified account didn't seem works.

I don't know if any wrong with my hsd conf and referenced here:
https://github.com/handshake-org/hsd/blob/master/etc/sample.conf
`index-tx: false 
index-address: false`

**Comment by pinheadmz** [comment]
That sounds like correct behavior to me - it's a list of transactions (no need for duplicates). If you want to see a list of the individual UTXO (coins) you should use `listunspent`:

https://hsd-dev.org/api-docs/#listunspent
