### ISSUE TITLE
How to claim airdrop

### ISSUE THREAD

**Issue by droslean** [handshake-org/hsd#397]
Hello,

How can I recover the coins which I have received from the initial airdrop?

**Comment by boymanjor** [comment]
If you think you were included in the airdrop, you can use the [hs-airdrop](https://github.com/handshake-org/hs-airdrop) tool to create an airdrop claim and redeem your coins. The requirements for inclusion can be found in the repo's README.

If you signed up for the faucet on handshake.org, a claim has likely already been submitted for you. Using a Handshake wallet, or a block explorer like https://hnscan.com, you can check the balance for the handshake faucet address you submitted to handshake.org.
