### ISSUE TITLE
Can you redeem after missing a reveal deadline?

### ISSUE THREAD

**Issue by bemusementpark** [handshake-org/hsd#403]
Is it possible to retrieve these coins?

It's kind of awkward that there's no option to bid without a blind, and that everyone needs to actively manage their bid, and come back in 1-5 days to reveal.

I think I lost some coins.

I'm not sure there's a good reason to prevent the withdrawal of all the coins. It'd just be like your bid was the same as the mask.

**Comment by pinheadmz** [comment]
If you do not reveal during the reveal period, the coins in the BID covenant are unspendable forever. The design is to require all users to reveal their bids before the auction ends. Without this mechanism, an attacker could place an endless amount of blinded bids and then only reveal the smallest one after seeing what other users' bid values were.

Of course you can always bid without a mask (set bid value = blind) but a reveal is still required to keep the auction game fair. It is a blind auction and all blind auctions have a bid phase and reveal phase.
