### ISSUE TITLE
Wallet restore misses transactions due to dense transaction activity: (lookahead / BIP44 gap limit)

### ISSUE THREAD

**Issue by mslipper** [handshake-org/hsd#407]
When you have lots of names (>100), rescanning the wallet causes names to be lost. Checkout the following screenshot:

![Screen Shot 2020-03-26 at 5 48 03 PM](https://user-images.githubusercontent.com/67953/77709967-f6339600-6f89-11ea-8079-8604cd02f510.png)

Here, I'm executing a wallet rescan then getting the list of names from the wallet once the rescan completes. (I look at the logs in another terminal to determine when the rescan is done.) As you can see, the number of names in the wallet changes even though the wallet itself hasn't made any new transactions. The number of names increases randomly whenever I rescan then get the names in the wallet.

**Comment by turbomaze** [comment]
Have you tried modifying the lookahead parameter to be very large? 1000 instead of the default 10 for instance. Can edit the max lookahead value in lib/wallet/account.js

**Comment by mslipper** [comment]
Yes, @pinheadmz mentioned this workaround to me and it fixed the issue. However, I still think that the real fix for this is within HSD itself given that it seems to be triggered by some kind of race condition.

**Comment by pinheadmz** [comment]
This issue is being tracked upstream in bcoin:

https://github.com/bcoin-org/bcoin/issues/835

**Comment by pinheadmz** [comment]
The hsd wallet gap limit issue discussion has bled into Bob-wallet: https://github.com/kyokan/bob-wallet/pull/165

Here are some references:

- [In bcoin and hsd the gap limit is 10](https://github.com/handshake-org/hsd/blob/master/lib/wallet/account.js#L53)
- [In BIP44, a standard value of 20 is defined ](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#address-gap-limit)
- [Breadwallet aka BRD uses 10 but really "looks for" 110 addresses](https://github.com/breadwallet/breadwallet-core/blob/42f2fa60b9c89933e9e8fc7d4c9dde4aa2916b18/support/BRBIP32Sequence.h#L43-L67)
- [Electrum seems to use 20 for receive](https://github.com/spesmilo/electrum/blob/4961020e01c515735bb885704fb85c7ae6c73ab1/electrum/wallet.py#L2332) ... but [10 for change](https://github.com/spesmilo/electrum/blob/4961020e01c515735bb885704fb85c7ae6c73ab1/electrum/wallet.py#L243)
- [Bitcoin Core generates 1000 addresses ahead of last-used index](https://github.com/bitcoin/bitcoin/blob/89899a344861c27ad31dc09334fa88ec9402dba4/src/wallet/scriptpubkeyman.h#L80-L81) ... [DEFAULT_KEYPOOL_SIZE](https://github.com/bitcoin/bitcoin/blob/89899a344861c27ad31dc09334fa88ec9402dba4/src/wallet/scriptpubkeyman.h#L470)


It seems to be a common work-around for users to just set the value to `1000` and in fact, Bob I think already does this. This will create a problem if users try to restore their balance from a different version of Bob or hsd however. So I think a standard is important. 

There are better solutions described in https://github.com/bcoin-org/bcoin/issues/835 and in fact [one unmerged patch in bcoin](https://github.com/bcoin-org/bcoin/commit/c6859b347bd6989c1eb87fc58e05b6fcc4b91c8b) avoids the issue by rescanning blocks every time a TX is found in a block.

The main issue is that bcoin/hsd uses bloom filters for rescanning [(even against a full node)](https://github.com/handshake-org/hsd/blob/master/lib/blockchain/chaindb.js#L1462) and these filters are updated *after* each block is scanned. We could just remove that optimization and probably a gap limit of 10 or 20 would be fine, but would slow down rescans.

Note that this is only an issue during rescan. During a regular `"block connect"` event, every tx in the block is checked [one at a time](https://github.com/handshake-org/hsd/blob/master/lib/wallet/walletdb.js#L2090-L2093) for a wallet-match.

## Solutions

1) Band-aid: bump `lookahead` to 1000 in hsd, make sure that wallets upgrading to latest version will generate those addresses as well, maybe include note about rescanning in the changelog after updating

2) Research the performance hit to rescanning if the bloom filter is removed and the `"block connect"` path is used instead

3) Research the performance hit (or other tradeoffs) of repeatedly rescanning a block once a wallet TX is found, adding to the address depth each time, until new TXs stop turning up
