### ISSUE TITLE
 How to calculate the hashrate according to the share

### ISSUE THREAD

**Issue by huwentao1** [handshake-org/hsd#410]
I know the hashrate calculate formula
```
hashrate = factor * share / time
```
This is btcpool provide some other coin factor.
[Calculte Hashrate](https://github.com/btccom/btcpool/issues/272)
Please tell me what is this coin factor. Thanks.

**Comment by pinheadmz** [comment]
This sounds like a detail you need to negotiate with your mining pool.
I'm not sure what any of these variables are supposed to represent.

You can get estimated network hash rate using your own full node:

https://hsd-dev.org/api-docs/#getmininginfo

**Comment by huwentao1** [comment]
Thank you, I am newbie, I want to use this to estimate the hashrate of the miners, not computing hashrate of the entire network.

"Factor" seems to be the number of times each share difficulty needs to be hashed. It should be a fixed value for a fixed algorithm, but I don't know how to calculate it, or where to find relevant information. 

If so, how is the computing power of the entire network calculated?It should be calculated from the shares submitted by all miners.

**Comment by huwentao1** [comment]
> This sounds like a detail you need to negotiate with your mining pool.
> I'm not sure what any of these variables are supposed to represent.
> 
> You can get estimated network hash rate using your own full node:
> 
> https://hsd-dev.org/api-docs/#getmininginfo

Thank you, I am newbie, I want to use this to estimate the hashrate of the miners, not computing hashrate of the entire network.

"Factor" seems to be the number of times each share difficulty needs to be hashed. It should be a fixed value for a fixed algorithm, but I don't know how to calculate it, or where to find relevant information.

If so, how is the computing power of the entire network calculated?It should be calculated from the shares submitted by all miners.

**Comment by pinheadmz** [comment]
You can probably find your answers on Bitcoin Stack Exchange:

https://bitcoin.stackexchange.com/search?q=hashrate

I'm going to close this issue since it is unrelated to operation of hsd.
