### ISSUE TITLE
Migration path for wallets affected by the change address bug

### ISSUE THREAD

**Issue by chjj** [handshake-org/hsd#414]
See:

- https://github.com/handshake-org/hsd/issues/411
- https://github.com/handshake-org/hsd/pull/413

Quoting my post:

> I think we should consider a migration path for affected wallets. I think a simple migration would be to regenerate and save all change addresses in the lookahead. The user will most likely have to rescan after that (whether to do this automatically or require user intervention is something I'm unsure of).

I'd like to get a migration out within the next 24 hours.

**Comment by pinheadmz** [comment]
Closed by #415
