### ISSUE TITLE
FreeBSD portability

### ISSUE THREAD

**Issue by chrisbgit** [handshake-org/hsd#42]
diff --git a/bin/hsd b/bin/hsd
index 5f478501..68e56c79 100755
--- a/bin/hsd
+++ b/bin/hsd
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 rl=0
 daemon=0
diff --git a/bin/hsw b/bin/hsw
index 6a56b2f2..8606de8c 100755
--- a/bin/hsw
+++ b/bin/hsw
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 rl=0
 daemon=0

**Comment by chrisbgit** [comment]
Added a pull request.

https://github.com/handshake-org/hsd/pull/45

**Comment by tynes** [comment]
Thank you for your PR, but that file was recently rewritten in nodejs
