### ISSUE TITLE
Socket Error when use testnet

### ISSUE THREAD

**Issue by rocqina** [handshake-org/hsd#432]
I execute the cmd "hsd --network=testnet --http-host='0.0.0.0' --listen=true --cors --no-auth --coinbase-address='hs1q8a7zl0gsp98cp7sjh4hpwan7t28kezfkc2c2qp' --daemon " to run had fullnode by testnet. By the way I use the cmd replaced "--network=main" for main network and it is ok.

and the output of debug.log as below:
[D:2020-04-17T02:51:04Z] (net) Connecting to aoihqqagbhzz6wxg43itefqvmgda4uwtky362p22kbimcyg5fdp54@172.104.214.189:45806.
[D:2020-04-17T02:51:04Z] (net) Error: Socket Error: ECONNREFUSED (ajk57wutnhfdzvqwqrgab3wwh4wxoqgnkz4avbln54pgj5jwefcts@172.104.177.177:45806)
[I:2020-04-17T02:51:04Z] (net) Removed loader peer (ajk57wutnhfdzvqwqrgab3wwh4wxoqgnkz4avbln54pgj5jwefcts@172.104.177.177:45806).
[D:2020-04-17T02:51:04Z] (net) Error: Socket Error: ECONNREFUSED (ajdzrpoxsusaw4ixq4ttibxxsuh5fkkduc5qszyboidif2z25i362@173.255.209.126:45806)
[D:2020-04-17T02:51:04Z] (net) Error: Socket Error: ECONNREFUSED (am2lsmbzzxncaptqjo22jay3mztfwl33bxhkp7icfx7kmi5rvjaic@139.162.183.168:45806)
[D:2020-04-17T02:51:04Z] (net) Error: Socket Error: ECONNREFUSED (aoihqqagbhzz6wxg43itefqvmgda4uwtky362p22kbimcyg5fdp54@172.104.214.189:45806)
[D:2020-04-17T02:51:07Z] (net) Connecting to am2lsmbzzxncaptqjo22jay3mztfwl33bxhkp7icfx7kmi5rvjaic@139.162.183.168:45806.
[I:2020-04-17T02:51:07Z] (net) Adding loader peer (am2lsmbzzxncaptqjo22jay3mztfwl33bxhkp7icfx7kmi5rvjaic@139.162.183.168:45806).
[D:2020-04-17T02:51:07Z] (net) Connecting to aoihqqagbhzz6wxg43itefqvmgda4uwtky362p22kbimcyg5fdp54@172.104.214.189:45806.
[D:2020-04-17T02:51:07Z] (net) Connecting to ajdzrpoxsusaw4ixq4ttibxxsuh5fkkduc5qszyboidif2z25i362@173.255.209.126:45806.
[D:2020-04-17T02:51:07Z] (net) Connecting to ajk57wutnhfdzvqwqrgab3wwh4wxoqgnkz4avbln54pgj5jwefcts@172.104.177.177:45806.
[D:2020-04-17T02:51:07Z] (net) Error: Socket Error: ECONNREFUSED (ajk57wutnhfdzvqwqrgab3wwh4wxoqgnkz4avbln54pgj5jwefcts@172.104.177.177:45806)
[D:2020-04-17T02:51:07Z] (net) Error: Socket Error: ECONNREFUSED (ajdzrpoxsusaw4ixq4ttibxxsuh5fkkduc5qszyboidif2z25i362@173.255.209.126:45806)
[D:2020-04-17T02:51:07Z] (net) Error: Socket Error: ECONNREFUSED (am2lsmbzzxncaptqjo22jay3mztfwl33bxhkp7icfx7kmi5rvjaic@139.162.183.168:45806)
[I:2020-04-17T02:51:07Z] (net) Removed loader peer (am2lsmbzzxncaptqjo22jay3mztfwl33bxhkp7icfx7kmi5rvjaic@139.162.183.168:45806).
[D:2020-04-17T02:51:07Z] (net) Error: Socket Error: ECONNREFUSED (aoihqqagbhzz6wxg43itefqvmgda4uwtky362p22kbimcyg5fdp54@172.104.214.189:45806)

**Comment by pinheadmz** [comment]
Please see https://github.com/handshake-org/hsd/issues/365

**Comment by rocqina** [comment]
Thanks a lot!

**Comment by rocqina** [comment]
@pinheadmz , I add the node ,but it looks like there is something wrong as below.
 
[D:2020-04-17T08:01:34Z] (wallet) Adding block: 15.
[D:2020-04-17T08:01:34Z] (chain) Memory: rss=54mb, js-heap=16/29mb native-heap=24mb
[I:2020-04-17T08:01:34Z] (chain) Block 00000000576e1f00cdd193e3465fb1cd999845cdcffa8283fef91becd197b448 (15) added to chain (size=351 txs=1 time=1.517678).
[D:2020-04-17T08:01:34Z] (net) Received full compact block 0000000082eb1beaf0d60274b96017eba7b7dd91f6492337ebb99179460076c5 (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806).
[D:2020-04-17T08:01:34Z] (wallet) Adding block: 16.
[D:2020-04-17T08:01:34Z] (chain) Memory: rss=55mb, js-heap=16/29mb native-heap=25mb
[I:2020-04-17T08:01:34Z] (chain) Block 0000000082eb1beaf0d60274b96017eba7b7dd91f6492337ebb99179460076c5 (16) added to chain (size=351 txs=1 time=1.363661).
[D:2020-04-17T08:01:34Z] (net) Received full compact block 000000007b3b5258cbadb7c22d4593b98f0663967805125e2a2fb8c09ea06573 (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806).
[D:2020-04-17T08:01:34Z] (wallet) Adding block: 17.
[D:2020-04-17T08:01:34Z] (chain) Memory: rss=55mb, js-heap=16/29mb native-heap=26mb
[I:2020-04-17T08:01:34Z] (chain) Block 000000007b3b5258cbadb7c22d4593b98f0663967805125e2a2fb8c09ea06573 (17) added to chain (size=351 txs=1 time=1.440798).




[D:2020-04-17T08:03:29Z] (hostlist) Writing hosts to /root/.hsd/testnet/hosts.json.
[D:2020-04-17T08:03:34Z] (net) Error: Peer is stalling (block). (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806)
[I:2020-04-17T08:03:34Z] (net) Removed loader peer (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806).
[D:2020-04-17T08:03:35Z] (net) Connecting to ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806.
[I:2020-04-17T08:03:35Z] (net) Adding loader peer (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806).
[I:2020-04-17T08:03:35Z] (net) Connected to ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806.
[D:2020-04-17T08:03:36Z] (peer) Received verack (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806).
[I:2020-04-17T08:03:36Z] (net) Received version (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806): version=1 height=17 services=11 agent=/hsd:2.0.2/
[D:2020-04-17T08:03:36Z] (peer) Version handshake complete (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806).
[I:2020-04-17T08:03:36Z] (peer) Initializing normal compact blocks (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806).
[D:2020-04-17T08:03:36Z] (peer) Requesting inv packet from peer with getblocks (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806).
[D:2020-04-17T08:03:36Z] (peer) Sending getblocks (hash=000000007b3b5258cbadb7c22d4593b98f0663967805125e2a2fb8c09ea06573, stop=0000000000000000000000000000000000000000000000000000000000000000).
[I:2020-04-17T08:03:36Z] (peer) Peer initialized compact blocks (mode=0, version=1) (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806).
[D:2020-04-17T08:03:36Z] (net) Ignoring getaddr from outbound node (ai3shxm76z2fvdhv5rvbriloabhsghr6v43mi3zmtlq75ocbeb4wg@142.93.64.216:45806).

**Comment by pinheadmz** [comment]
This is all totally correct. The testnet chain has zero hashrate and therefore only 17 blocks. All the errors you see here are hsd trying to connect to other hsd nodes, which there are basically none on testnet.

**Comment by rocqina** [comment]
So if I want to test resolve block to network, I can not do it on testnet. Right?

**Comment by pinheadmz** [comment]
I don't understand what you mean by "resolve block to network" ?

**Comment by rocqina** [comment]
I want to test mine on testnet when the miner finds a new block and submits the resolved block to full node.

**Comment by pinheadmz** [comment]
You can mine on testnet.

**Comment by rocqina** [comment]
OK, Thanks!

**Comment by ltfschoen** [comment]
I encountered the same error. It was because I was using `--network=testnet` instead of `--network=main`
