### ISSUE TITLE
How get address and amount from transaction

### ISSUE THREAD

**Issue by huwentao1** [handshake-org/hsd#439]
The function I want to achieve is to pass in an address and an amount, and then judge whether the transaction is in a block.
I get all transaction information of the block through the rpc command getblock:
```
hsd-rpc getblock 000000000000000981a1d10f31ecd02e0cca53b7dff38cc8ea4b9557d74c2e82 true true 
```

Then I took a vout information for comparison and found that there is no address in it, only a hash. What does this hash mean?How can I get the address through this hash?
```
{
    "vout": [
        {
            "value": 0.4789,
            "n": 1,
            "address": {
                "version": 0,
                "hash": "3edc998ae3645b4cdf03a098f31419fee504fceb",
            },
            "covenant": {"type": 0, "action": "NONE", "items": []},
        },
    ]
}
```

**Comment by pinheadmz** [comment]
Here is an explanation:

https://github.com/handshake-org/hs-airdrop/issues/36#issuecomment-586669062

I think we could improve the API output. Some API calls represent address as strings, others like this. 

Also if you are just interested in looking up TX by address, there is API call for this exact function. It requires running hsd with `--index-address`:

https://hsd-dev.org/api-docs/?shell--curl#get-tx-by-address

**Comment by huwentao1** [comment]
> Here is an explanation:
> 
> [handshake-org/hs-airdrop#36 (comment)](https://github.com/handshake-org/hs-airdrop/issues/36#issuecomment-586669062)
> 
> I think we could improve the API output. Some API calls represent address as strings, others like this.
> 
> Also if you are just interested in looking up TX by address, there is API call for this exact function. It requires running hsd with `--index-address`:
> 
> https://hsd-dev.org/api-docs/?shell--curl#get-tx-by-address

I think I found a way to convert the address. The following is the python code I implemented
```python
import bech32

version = 0
hash = "3e80585bb592b510c71b4130048cc89cae36414a"


def get_address_by_hash(hrp, version, hash):
    hash_arr = []
    start = 0
    for index in range(len(hash) // 2):
        hash_arr.append(int(hash[start : (start + 2)], 16))
        start += 2
    return bech32.encode(hrp, version, hash_arr)


print(get_address_by_hash("hs", version, hash))
```

I closed this issue, thank you.
