### ISSUE TITLE
rpc getrawtransaction (possibly others) display address as separate version/hash values

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#442]
This is becoming a FAQ.

See: https://github.com/handshake-org/hs-airdrop/issues/36#issuecomment-586669062

and this question from telegram:

```
lever W, [May 3, 2020 at 9:09:16 AM]:
@pinheadmz Hi boss,  i got vout of tx by "getrawtransaction", but i found there is no address

{
        "value": 26876.53865,
        "n": 3,
        "address": {
          "version": 0,
          "hash": "f608789d349fb47c5de198900f85338f84ff2cc8"
        },
        "covenant": {
          "type": 0,
          "action": "NONE",
          "items": []
        }
      }
```

We should go through all the API responses and make sure all addresses are represented as strings, I'm not sure if there's any reason to express them separately like this.

**Comment by tynes** [comment]
I think we are going to need to add an additional field to prevent breaking changes.

Some possibilities:

- `addr`
- `addressbech32`
- `addrstring`

**Comment by pinheadmz** [comment]
Yes agreed, how about simply...

```
        "address": {
          "version": 0,
          "hash": "f608789d349fb47c5de198900f85338f84ff2cc8",
          "string": "hs1q9jtymgvegg7shxgqtejrvq7d6ky4sy6f4xm3xz"
        },
```

**Comment by tynes** [comment]
I like that idea and can be achieved in a very simple way here:

https://github.com/handshake-org/hsd/blob/1d7251957dd5ce35eb173c3fcdca0ca2479dcb83/lib/node/rpc.js#L2869-L2873
