### ISSUE TITLE
Unable to send

### ISSUE THREAD

**Issue by matiasinsaurralde** [handshake-org/hsd#450]
Hi, when checking my balance I get the following output:

```
% ./bin/hsw-cli balance
{
  "account": -1,
  "tx": 1,
  "coin": 1,
  "unconfirmed": 4246894314,
  "confirmed": 4246894314,
  "lockedUnconfirmed": 0,
  "lockedConfirmed": 0
}
```
When trying to send I get this error:
```
% ./bin/hsw-cli send hsxxxxxxxxxxxxxxxxxxxxxxx 1000
Error: Not enough funds. (available=0.0, required=1000.0074)
    at WalletClient.request (/Users/matias/dev/hsd/hs-client-0.0.8/hs-client/node_modules/bcurl/lib/client.js:213:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
1) Is the "balance" command output ok? Is it expected to see "-1" in the account field?
2) Why the send command fails if the balance shows a positive number? Could it be related to # of confirmations? I've received the HNS like 10 hours ago.

Thanks

**Comment by pinheadmz** [comment]
Is this an airdrop claim? They take 100 blocks to mature, like coinbase transactions for miners.

**Comment by matiasinsaurralde** [comment]
Hi, yes, just confirmed it.
Thanks for the clarification
