### ISSUE TITLE
Unable execute ./hsd

### ISSUE THREAD

**Issue by yokosogithub** [handshake-org/hsd#456]
System:ubuntu
Node:10.15.0
NPM:6.4.1
When I execute ./hsd, it shows error:

/usr/local/lib/node_modules/hsd/node_modules/loady/lib/loady.js:121
  throw err;
  ^
Error: Could not locate the bindings file. Tried:
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/build/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/build/Debug/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/build/Release/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/out/Debug/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/Debug/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/out/Release/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/Release/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/build/default/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/compiled/10.15.0/linux/x64/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/addon-build/release/install-root/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/addon-build/debug/install-root/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/addon-build/default/install-root/leveldown.node
 - /usr/local/lib/node_modules/hsd/node_modules/bdb/lib/binding/node-v64-linux-x64/leveldown.node
    at bindings (/usr/local/lib/node_modules/hsd/node_modules/loady/lib/loady.js:116:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/hsd/node_modules/bdb/lib/level.js:9:33)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/hsd/node_modules/bdb/lib/bdb.js:13:15)

**Comment by pinheadmz** [comment]
Did you run `npm install` first? See the readme as well for requirements.

**Comment by yokosogithub** [comment]
Yes,I run `npm install` first.

**Comment by pinheadmz** [comment]
Were there any errors? You could try `npm rebuild`

**Comment by tynes** [comment]
Which version of `hsd` are you running?

**Comment by yokosogithub** [comment]
> Which version of `hsd` are you running?

2.1.5

**Comment by yokosogithub** [comment]
> Were there any errors? You could try `npm rebuild`

No, there weren't any errors.

**Comment by pinheadmz** [comment]
> /usr/local/lib/node_modules/hsd/node_modules/bdb/build/leveldown.node

Looks like you installed globally? i.e. `npm i -g` ?

Where exactly "are" you when you command `./hsd` ?

**Comment by yokosogithub** [comment]
> > /usr/local/lib/node_modules/hsd/node_modules/bdb/build/leveldown.node
> 
> Looks like you installed globally? i.e. `npm i -g` ?
> 
> Where exactly "are" you when you command `./hsd` ?

No, I installed it locally.

**Comment by tynes** [comment]
Make sure to have a C++ compiler installed on your machine along with node-gyp. These are usually dependencies of npm. Try the command `$ npm rebuild` in the root of the git repo.

Please try to share some more information about the process you took to install, it will make it much easier to help you.

**Comment by yokosogithub** [comment]
I can run `./bin/hsd` normally.

**Comment by pinheadmz** [comment]
@yokosogithub you are not really providing us with enough details to help you.

> I can run ./bin/hsd normally.

So there is no issue and everything is fine then?

> When I execute ./hsd, it shows error ...

What is the `pwd` when you are running these two commands?

My advice is, cd to the root of the hsd repo directory and `npm install -g`.
This will put all the hsd `bin` files on your global PATH, and you should be able to run `hsd` as a command from anywhere in your system.

**Comment by tynes** [comment]
Feel free to reopen with more details of your problem if you are still facing it.
