### ISSUE TITLE
Method not found: getwalletinfo

### ISSUE THREAD

**Issue by huwentao1** [handshake-org/hsd#458]
node run:
```
hsd  --http-host=0.0.0.0  --api-key=xxx --coinbase-address=xxxx   --index-tx=1
```
method:
```
mac ~/hwt/api_project/worker_job/pool_job % hsd-rpc --api-key=xxx getwalletinfo
Method not found: getwalletinfo.
mac ~/hwt/api_project/worker_job/pool_job % hsd-rpc --api-key=xxx listtransactions 
Method not found: listtransactions.
```

How do I start the node to use wallet related commands

**Comment by pinheadmz** [comment]
You need to use hsw-rpc for wallet commands (the wallet API is separate from the node API)

See https://hsd-dev.org/api-docs/?shell--curl#getwalletinfo

**Comment by huwentao1** [comment]
> You need to use hsw-rpc for wallet commands (the wallet API is separate from the node API)
> 
> See https://hsd-dev.org/api-docs/?shell--curl#getwalletinfo

First of all thank you for providing a link to this document

But I don’t particularly understand that document api. What I want to do now is to create a wallet address and then perform some transfer operations through commands.

I got the following information through the command getwalletinfo, I am very confused why balance is 0, because the --coinbase-address I set above actually has a balance.
```
mac ~/hwt/api_project/worker_job/pool_job % hsw-rpc getwalletinfo --api-key=xxx
{
  "walletid": "primary",
  "walletversion": 6,
  "balance": 0,
  "unconfirmed_balance": 0,
  "txcount": 0,
  "keypoololdest": 0,
  "keypoolsize": 0,
  "unlocked_until": 0,
  "paytxfee": 0
}
```

If I want to transfer money online via the rpc command, how should I start the node and what methods should I call?

**Comment by tynes** [comment]
Are you playing around on regtest? Try:

```bash
$ hsw-cli account get default
```

Take the `receiveAddress` from there, then call:

```bash
$ hsd-rpc generatetoaddress $block_count $address
```
Where `block_count` is the number of blocks to mine and `address` is your `receiveAddress`
This will mine some coins for you to send. But it will only work on `regtest`.

Source:
https://github.com/tynes/hsd-authns-scripts/blob/426caeaa2dfa8166e66b483c8148d88d51fbd81d/buy-name.sh#L23

If you are on mainnet with an actual wallet, you need to add the address to your wallet and then rescan.
https://hsd-dev.org/api-docs/#import-address
https://hsd-dev.org/api-docs/#wallet-rescan

**Comment by huwentao1** [comment]
> Are you playing around on regtest? Try:
> 
> ```shell
> $ hsw-cli account get default
> ```
> 
> Take the `receiveAddress` from there, then call:
> 
> ```shell
> $ hsd-rpc generatetoaddress $block_count $address
> ```
> 
> Where `block_count` is the number of blocks to mine and `address` is your `receiveAddress`
> This will mine some coins for you to send. But it will only work on `regtest`.
> 
> Source:
> https://github.com/tynes/hsd-authns-scripts/blob/426caeaa2dfa8166e66b483c8148d88d51fbd81d/buy-name.sh#L23
> 
> If you are on mainnet with an actual wallet, you need to add the address to your wallet and then rescan.
> https://hsd-dev.org/api-docs/#import-address
> https://hsd-dev.org/api-docs/#wallet-rescan

Thank you for the documentation. I tested it directly on the mainnet, and I have successfully transferred it with sendmany. 
I think it may not be very convenient because you can only transfer from one account to another address, you can't transfer to another address through the address.
I will close this issue.
