### ISSUE TITLE
 What is the hns basic block reward

### ISSUE THREAD

**Issue by huwentao1** [handshake-org/hsd#459]
By querying the documentation, I know that btc is a halving algorithm. Now the basic block reward is 6.25. Most of the hns block rewards information is more than 2000 hns.The composition of rewards
```
2000hns + fee
```
 Is the basic block reward of hns 2000?Will this value change ?

**Comment by pinheadmz** [comment]
Yes, Handshake has a halving interval of about 3.5 years.

Lots of details here: https://hsd-dev.org/guides/protocol.html
