### ISSUE TITLE
Is there a rpc command to transfer from a fixed address to other many address?

### ISSUE THREAD

**Issue by huwentao1** [handshake-org/hsd#462]
rpc command: sendmany 
![image](https://user-images.githubusercontent.com/43719888/82790921-751c5080-9e9f-11ea-8271-42164665667b.png)

The first parameter can only be an account, but I hope to transfer an address from it.
If there is no rpc command, is there a way to achieve such a function

**Comment by pinheadmz** [comment]
> transfer an address

What do you mean? Coins and names can be transferred in a Handshake transaction. Addresses aren't something you can transfer on the blockchain.

**Comment by huwentao1** [comment]
> do you mean? Coins and names can be transferred in a Handshake transaction. Addresses aren't something you can transfer on the blockc



> > transfer an address
> 
> What do you mean? Coins and names can be transferred in a Handshake transaction. Addresses aren't something you can transfer on the blockchain.

I made a deal like this
```
{"hs1qpvgpf3s85rqvpuq66mxfjnk6e5yj5k4jknq3qx": 0.02, "hs1qykqwncvestcx5nxhxjlqqs8nsn9a94ugy7xhqt": 0.2}
```
But I found this after querying on the browser
![image](https://user-images.githubusercontent.com/43719888/82855069-dcd4a900-9f3c-11ea-8d07-4792d5d8f885.png)

I hope the address in the red box will always be fixed during sendmany, but in fact it changes every time

**Comment by pinheadmz** [comment]
I think we discussed this in telegram chat. If you want to specify each input and output you could use https://hsd-dev.org/api-docs/#createrawtransaction or use hsd as a library and write a script that constructs the transaction you need.

There may be much easier options available to you using the default tool set, depending on your use case. You could send from accounts instead of individual addresses for example, which is best practice anyway and how a lot of businesses use the BIP44 wallet structure (one account per client, etc)

**Comment by huwentao1** [comment]
> I think we discussed this in telegram chat. If you want to specify each input and output you could use https://hsd-dev.org/api-docs/#createrawtransaction or use hsd as a library and write a script that constructs the transaction you need.
> 
> There may be much easier options available to you using the default tool set, depending on your use case. You could send from accounts instead of individual addresses for example, which is best practice anyway and how a lot of businesses use the BIP44 wallet structure (one account per client, etc)


Thank you very much for the suggestions. I also checked some information and performed the following operations through rpc, but it was never successful.
1. listunspent

```
{
    "result": [
        ...
        {
            "txid": "382a717a471f20e8a3d3be14c65a3c0c43ade56a2d3cf4d6e862f60930b20688",
            "vout": 3,
            "address": "hs1q63p2z57gn9w99p7pdgegyvtx9ns7a9cvygg3ss",
            "account": "default",
            "amount": 3.4966,
            "confirmations": 273,
            "spendable": true,
            "solvable": true,
        },
        ...
    ],  
}
```
2. Construct some variable information

```
amounts = {
    "hs1qpvgpf3s85rqvpuq66mxfjnk6e5yj5k4jknq3qx": 0.02,
    "hs1qykqwncvestcx5nxhxjlqqs8nsn9a94ugy7xhqt": 0.01,
    "hs1q63p2z57gn9w99p7pdgegyvtx9ns7a9cvygg3ss": 3.1399,  # Set the transfer-out address to a fixed change address
}
txid_list = [
    {
        "txid": "382a717a471f20e8a3d3be14c65a3c0c43ade56a2d3cf4d6e862f60930b20688",
        "vout": 3,
    }
]
inputs = [
    {
        "txid": "382a717a471f20e8a3d3be14c65a3c0c43ade56a2d3cf4d6e862f60930b20688",
        "vout": 3,
        "address": "hs1q63p2z57gn9w99p7pdgegyvtx9ns7a9cvygg3ss",
        "amount": 3.4966,
    }
]
```
3. createrawtransaction
```
unsign_hash = hns_rpc.createrawtransaction(txid_list, amounts)
0000000001382a717a471f20e8a3d3be14c65a3c0c43ade56a2d3cf4d6e862f60930b2068803000000ffffffff03204e00000000000000140b1014c607a0c0c0f01ad6cc994edacd092a5ab20000102700000000000000142580e9e19982f06a4cd734be0040f384cbd2d78800003ce92f00000000000014d442a153c8995c5287c16a328231662ce1ee970c00000000000000
```
4. decoderawtransaction
```
{
    "txid": "2c9b670a947ba65d59512ade28cf25a38e92cef8348c0fe022f8fd7afb511474",
    "hash": "50c0c22089437b609627f6aa39450cb769b43935cb732e999cb25cd3e506e967",
    "size": 147,
    "vsize": 147,
    "version": 0,
    "locktime": 0,
    "vin": [
        {
            "coinbase": False,
            "txid": "382a717a471f20e8a3d3be14c65a3c0c43ade56a2d3cf4d6e862f60930b20688",
            "vout": 3,
            "txinwitness": [],
            "sequence": 4294967295,
        }
    ],
    "vout": [
        {
            "value": 0.02,
            "n": 0,
            "address": {
                "version": 0,
                "hash": "0b1014c607a0c0c0f01ad6cc994edacd092a5ab2",
            },
            "covenant": {"type": 0, "action": "NONE", "items": []},
        },
        {
            "value": 0.01,
            "n": 1,
            "address": {
                "version": 0,
                "hash": "2580e9e19982f06a4cd734be0040f384cbd2d788",
            },
            "covenant": {"type": 0, "action": "NONE", "items": []},
        },
        {
            "value": 3.1399,
            "n": 2,
            "address": {
                "version": 0,
                "hash": "d442a153c8995c5287c16a328231662ce1ee970c",
            },
            "covenant": {"type": 0, "action": "NONE", "items": []},
        },
    ],
    "blockhash": None,
    "confirmations": 0,
    "time": 0,
    "blocktime": 0,
}
```
5. walletpassphrase, signrawtransaction sign

Because I can't get the private key of the wallet, because I unlock it through walletpassphrase and then sign. 
```
hns_wallet_rpc.walletpassphrase("xxxx", 60)
sign_tx_info = hns_rpc.signrawtransaction(unsign_hash, inputs)
```
The signature has always failed. This is the first time I have constructed a rawtransaction. Did I do something wrong?

Below is the code I implemented
```
txid_list = [
    {
        "txid": "382a717a471f20e8a3d3be14c65a3c0c43ade56a2d3cf4d6e862f60930b20688",
        "vout": 3,
    }
]
amounts = {
    "hs1qpvgpf3s85rqvpuq66mxfjnk6e5yj5k4jknq3qx": 0.02,
    "hs1qykqwncvestcx5nxhxjlqqs8nsn9a94ugy7xhqt": 0.01,
    "hs1q63p2z57gn9w99p7pdgegyvtx9ns7a9cvygg3ss": 3.1399,
}
inputs = [
    {
        "txid": "382a717a471f20e8a3d3be14c65a3c0c43ade56a2d3cf4d6e862f60930b20688",
        "vout": 3,
        "address": "hs1q63p2z57gn9w99p7pdgegyvtx9ns7a9cvygg3ss",
        "amount": 3.4966,
    }
]
unsign_hash = hns_rpc.createrawtransaction(txid_list, amounts)
hns_wallet_rpc.walletpassphrase("xxxxx", 60)
sign_tx_info = hns_rpc.signrawtransaction(unsign_hash, inputs)

if not sign_tx_info.get("complete"):
    print("transaction is wrong")
else:
    print(hns_rpc.sendrawtransaction(sign_tx_info.get("hex")))
```

**Comment by pinheadmz** [comment]
> hns_wallet_rpc.walletpassphrase("xxxx", 60)
> sign_tx_info = hns_rpc.signrawtransaction(unsign_hash, inputs)

> The signature has always failed. This is the first time I have constructed a rawtransaction. Did I do something wrong?

Yes. [See the API for `signrawtransaction`](https://hsd-dev.org/api-docs/#signrawtransaction): it requires a private key.

You might be better off using the wallet API commands:

https://hsd-dev.org/api-docs/#create-a-transaction

https://hsd-dev.org/api-docs/#sign-transaction

Although I'm going to plead with you again -- do not reuse change addresses, do not create every transaction with the same change address. There is a really good reason BIP44 was standardized, and why companies handling hundreds of thousands of users with millions of transactions use BIP44 accounts. I don't entirely understand your use case but I'm afraid you're going to try to write your own wallet software and make expensive mistakes. The fact that you misunderstand how to use `signrawtransaction` suggests to me that, at least to start, use the default hsd wallet functionality. Its really quite good!

**Comment by huwentao1** [comment]
> Yes. See the API for signrawtransaction: it requires a private key.

I see that the private key parameter written in the document does not seem to have a required field to mark it.But anyway, I can't get our private key. I will try to sign the wallet API commands later

>  do not reuse change addresses, do not create every transaction with the same change address. 

I think this suggestion is very good. We also hope to follow this standard.
But how to say, now every day the finance will roughly review the bills of each currency on the block browser, but there is no detailed transaction information of the account on the block browser. Therefore, we choose to fix the change address.

Finally, thank you very much for your help recently. We have solved this problem by changing the sendmany method of hsd. I will close this issue, thank you very much.

**Comment by pinheadmz** [comment]
You can also use the wallet API to get the balance of an entire _account_:

https://hsd-dev.org/api-docs/?shell--cli#get-account-information

**Comment by huwentao1** [comment]
> You can also use the wallet API to get the balance of an entire _account_:

It is indeed possible to get the balance, but this is still very different from our daily bill analysis process. In fact, I don’t particularly understand why there are many coins that like to change addresses (maybe for security), but this is true caused us a lot of trouble(Whether it’s the level of transfers or the level of checking bills).
Maybe I still need to learn more currency related knowledge to understand this change address. Finally , Thank you very much for your recent help.
