### ISSUE TITLE
Non-deterministic tests

### ISSUE THREAD

**Issue by pinheadmz** [handshake-org/hsd#473]
See for example https://github.com/handshake-org/hsd/commit/a3049d5b7e7feb431419e3c4d092bb71e17c86fc

Lots of PRs are failing CI test suite due to timeout errors or in some cases race conditions in the test between the node and wallet.

```
  1) HTTP
       should generate 10 blocks from RPC call:

      Error: Request timed out.

      this.finish(new Error('Request timed out.'));
                  ^

      at Timeout.timeout.setTimeout (/home/circleci/repo/node_modules/brq/lib/request.js:376:19)
      at ontimeout (timers.js:427:11)
      at tryOnTimeout (timers.js:289:5)
      at listOnTimeout (timers.js:252:5)
      at Timer.processTimers (timers.js:212:10)
```

**Comment by tuxcanfly** [comment]
Hmm, could be just slower hardware on the CI instances. iirc there was no way to configure timeout for `hs-client` otherwise we could try that. FWIW I only bumped up the timeouts in my branch and haven't seen a failure so far.

https://github.com/tuxcanfly/hsd/pull/4
