### ISSUE TITLE
"Reason: TX exceeds maximum unconfirmed ancestors"

### ISSUE THREAD

**Issue by abrkn** [handshake-org/hsd#474]
I'm seeing this error, thrown at https://github.com/handshake-org/hsd/blob/89d3ab4c81969e6e14306d567c8f1411ad36c254/lib/wallet/wallet.js#L3401 when sending HSD

**Comment by pinheadmz** [comment]
This is a standardness rule inherited from Bitcoin that prevents chains of transactions that spend the unconfirmed change output of a previous transaction. It will happen if, for example, the wallet only has a single confirmed UTXO and then tries to create more than 50 new transactions before any change outputs are confirmed.

The best way to avoid this is with manual wallet strategy: If you have a single 10,000 HNS coin, send yourself 100 x 100 HNS transactions and make sure they all confirm before continuing.

More details about this policy can be found on Bitcoin stack exchange:

https://bitcoin.stackexchange.com/questions/62900/how-many-unconfirmed-childs-can-i-have

https://bitcoin.stackexchange.com/questions/59178/64-too-long-mempool-chain

https://bitcoin.stackexchange.com/questions/90344/resolve-btc-long-mem-pool-many-unconfirmed-tx

**Comment by pinheadmz** [comment]
Closing this now due to inactivity and since I do not believe it is a hsd issue. Please feel free to re-open or add more comments if anything else comes up.

**Comment by RobertLowe** [comment]
@pinheadmz can you elaborate on this a bit more. Do you mean 1 wallet with 10000hns, that transfers itself 100x100hns? Or do you mean create 100 wallets with 100hns each?

**Comment by pinheadmz** [comment]
@RobertLowe i meant the first strategy: If you have a wallet with one big coin (1,000,000 HNS) and then try to send too many transactions before the next block, you end up with a long chain that eventually breaks the policy rule:

This diagram represents 3 transactions in the mempool spending a chain of unconfirmed change outputs. If this chain gets too long (51) transactions will be rejected from your peer's mempools.

```
1000000 HNS -- Bob (1 HNS)
            \- Change (999999 HNS) -- Charlie (1 HNS)
                                   \- Change (999998 HNS) -- David (1 HNS)
                                                          \- Change (999997 HNS) ...
```

Over time, imagine this user sends themself 100 x 10000 HNS and waits for them to confirm. Then the above graph looks like this:

```
10000 HNS -- Bob (1 HNS)
          \- Change (9999 HNS)

10000 HNS -- Charlie (1 HNS)
          \- Change (9999 HNS)

10000 HNS -- David (1 HNS)
          \- Change (9999 HNS)
```
