### ISSUE TITLE
bslint as dependency causes vulnerabilities log on install

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#489]
I know that this is very common in the JavaScript space, but now that `bslint` is a `devDependency`, this error message logs on an `npm install`:

```
found 6 vulnerabilities (2 low, 1 moderate, 2 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```
Maybe there is a way we can have the Github actions install `bslint` as a prehook to the installation process so that we don't have to worry about this locally.

**Comment by pinheadmz** [comment]
Damn I got https://github.com/bcoin-org/bslint and https://github.com/chjj/bslint/ mixed up. The chjj repo is what's published to npm and although the dependencies are committed in the git repo, we still need to heed the security warnings. I guess there's a reason the linter was never added to deps before :-( Will have to install separately in the github workflow.
