### ISSUE TITLE
are these keys meant to be private?

### ISSUE THREAD

**Issue by lts-rad** [handshake-org/hsd#49]
https://github.com/handshake-org/hsd/blob/016c48726135725290279de858cf5bd32bf92e76/lib/dns/key.js#L14

**Comment by boymanjor** [comment]
No, these keys are the HNS root zone's key/zone signing keys. Essentially, the entire network shares these keys. They need to be embedded in each full node so dnnsec rrsets can be signed.

**Comment by lts-rad** [comment]
please correct my understanding here, but if these secret keys are publicly known theres no security provided by the signing. there might be an architectural flaw in the design
