### ISSUE TITLE
Disable CircleCI

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#491]
The CircleCI configuration was removed in https://github.com/handshake-org/hsd/pull/484 and I think it needs to be disabled in the CircleCI dashboard because it continues to run and fail because there is no config. Every commit from now on will have a red x next to it until this is disabled.

**Comment by pinheadmz** [comment]
Ok I think I figured this out. The circle settings have changed and dont match docs any more but I opened a test PR:

https://github.com/handshake-org/hsd/pull/492

And it looks like only github workflows is running now.

**Comment by pinheadmz** [comment]
Merged a comments-only PR to master, yes CircleCI is definitely not running builds any more.
