### ISSUE TITLE
corrupt wallet database after upgrading to v2.2.0, can't recover from mnemonic

### ISSUE THREAD

**Issue by ca98am79** [handshake-org/hsd#504]
After upgrading to v.2.2.0 hsd crashed when I tried to start it, with this message in the log:
`Error: Corruption: not an sstable (bad magic number)`

I wasn't able to figure out how to resolve this, so I ran a clean install of hsd on MacOS with the following:

```
$ git clone git://github.com/handshake-org/hsd.git
$ cd hsd
$ npm install --production
$ ./bin/hsd
```

After the blockchain is synced, I restored my wallet with the following command:

`./bin/hsw-cli mkwallet old_wallet --mnemonic=[mnemonic] --passphrase=[passphrase]`

Then, at the advice of @pinheadmz I changed the [account.js lookahead](https://github.com/handshake-org/hsd/blob/master/lib/wallet/account.js#L53) value to 1000 and restart hsd.

Then I did a rescan:

`./bin/hsw-cli rescan`

`getwalletinfo` shows only 16 txs:

```{
  ...
  "txcount": 16,
  "height": 30155
}
```

so I rescan again.  In the log, I see it scan through each block.  
`getwalletinfo` shows 28 txs now, but this is much lower than the number of transactions I did in this wallet:

```{
   ...
  "txcount": 28,
  "height": 30156
}
```

3rd rescan:

```{
   ...
  "txcount": 59,
  "height": 30156
}
```

4th rescan:

```{
   ...
  "txcount": 76,
  "height": 30156
}
```

5th rescan:

```{
   ...
  "txcount": 93,
  "height": 30156
}
```

6th rescan:

```{
   ...
  "txcount": 116,
  "height": 30156
}
```

7th rescan:

```{
   ...
  "txcount": 128,
  "height": 30157
}
```

8th rescan:

```{
   ...
  "txcount": 289,
  "height": 2977
}
```

Notice with this last rescan the `height` of the wallet dropped down to 2977.  There were a lot of `[warning] (wallet) Rescan block too high` messages in the log with the last rescan.

9th rescan:

```{
   ...
  "txcount": 349,
  "height": 5581
}
```

10th rescan:

```{
   ...
  "txcount": 361,
  "height": 5581
}
```

11th rescan:

```{
   ...
  "txcount": 390,
  "height": 5581
}
```

12th rescan:

```{
   ...
  "txcount": 409,
  "height": 5581
}
```

13th rescan:

```{
   ...
  "txcount": 420,
  "height": 5581
}
```

14th rescan:

```{
   ...
  "txcount": 420,
  "height": 5581
}
```

Nothing changed with this last rescan.  I try again:

15th rescan:

```{
   ...
  "txcount": 420,
  "height": 5581
}
```

Nothing changed again with this last rescan.  I try again:

16th rescan:

```{
   ...
  "txcount": 420,
  "height": 5581
}
```

Starting to look bleak.  Let's give it another shot:

17th rescan:

```{
   ...
  "txcount": 420,
  "height": 5581
}
```

Same thing.  Nothing changes after attempts 18, 19, 20 and 21...

I can't seem to recover my wallet.   Does anyone have ideas or suggestions?  Thanks!

**Comment by turbomaze** [comment]
Could you confirm that recovery works as expected on the prior version of HSD? Do you know the correct value for your # coins and confirmed balance/locked balance?

**Comment by ca98am79** [comment]
thanks, with help from @pinheadmz I was able to successfully restore.  We're not sure what the issue was, but we were able to solve it by removing the .hsd/wallet folder, adding the wallet back with mnemonic.  I then did:
`./bin/hsw-cli rescan`

```
[debug] (wallet-http) Request for method=PUT path=/wallet/old_wallet (127.0.0.1).
[info] (wallet) Created account old_wallet/default/0.
[info] (wallet) Wallet initialized (old_wallet).
[info] (wallet) Created wallet old_wallet in WalletDB.
[debug] (wallet-http) Request for method=POST path=/rescan (127.0.0.1).
[info] (wallet) Rolled back to same height (30164).
[info] (wallet) WalletDB is scanning 1 blocks.
[info] (chaindb) Scanning from block 00000000000000086722c01557939fd5b2b8eaccce6c2a9df1720d66eeca41f0.
[info] (chaindb) Scanning block 00000000000000086722c01557939fd5b2b8eaccce6c2a9df1720d66eeca41f0 (30164).
[debug] (wallet) Adding block: 30164.
[warning] (wallet) Already saw WalletDB block (30164).
[info] (chaindb) Finished scanning 1 blocks.
```

It only scanned 1 block.  So then we did:

`./bin/hsw-cli rescan 0`

It then scanned all the blocks, and after that the transaction count (1000+) is correct and I have access to my wallet.
