### ISSUE TITLE
Transaction Fee Market

### ISSUE THREAD

**Issue by tynes** [handshake-org/hsd#51]
Based on the comment in `lib/mempool/fees.js`:
``` 
 * Ported from:
 * https://github.com/bitcoin/bitcoin/blob/master/src/policy/fees.cpp`
```

and these 2 files being very similar from a quick glance:
- https://github.com/handshake-org/hsd/blob/master/lib/mempool/fees.js
- https://github.com/bcoin-org/bcoin/blob/master/lib/mempool/fees.js

it appears as if handshake is using the same transaction fee structure as bitcoin.

Has any thought and consideration gone into improving the transaction fee system to help ease volatility in the fee market?

Vitalik has come out with some interesting work on transaction fee markets recently, see: https://github.com/zcash/zcash/issues/3473

Curious to start a discussion around any pros/cons around different types of fee markets to see if some of Vitalik's ideas would be useful in the handshake protocol

**Comment by smcki012** [comment]
Would love to personally see this discussed as well. I wouldn't be surprised if @chjj hasn't already thought about this.

**Comment by tynes** [comment]
Irrelevant.
