### ISSUE TITLE
Connection time out while setting up node

### ISSUE THREAD

**Issue by luongthomas** [handshake-org/hsd#52]
Attempting to set up a full node but coming across errors that mention that it is unable to connect to certain IP addresses.

Here is a log.
https://gist.github.com/luongthomas/f35c761a0ddefcd0cee891a25b385574

I"m running this on MacOS High Sierra Version 10.13.6
npm version 6.2.0

Please let me know if you need additional details.

**Comment by tynes** [comment]
Those logs look normal to me. To be sure, try running `hsd-cli info` while the node is running.

There are various sorts of disconnects and timeouts in the p2p networking

**Comment by luongthomas** [comment]
Here is the output from `hsd-cli info`

https://gist.github.com/luongthomas/e802fff5c97214cc46e690a587049f01

**Comment by tynes** [comment]
See `.chain.progress`? It is equal to `1`, which means you are 100% synced to the chain. All is good for you 👍

**Comment by tynes** [comment]
Any other questions @luongthomas? Otherwise we can close this issue

**Comment by luongthomas** [comment]
Thanks @tynes.  All is good now and we can close this issue
