### ISSUE TITLE
New height notify

### ISSUE THREAD

**Issue by ruyichang** [handshake-org/hsd#527]
Hi,
Does HSD node have any interface methods to notify mining Pool when switching new heights?

**Comment by pinheadmz** [comment]
hsd, like bcoin, has a bunch of event notifications. They are currently best documented [here](https://hsd-dev.org/guides/events.html) and in the api-docs [here](https://hsd-dev.org/api-docs/#sockets). There are events for new blocks both conencting and disconnecting (in case of reorg).

In particular, I had a PR open for hs-miner that would listen for `block connect` events to restart the miner with a new block template: https://github.com/handshake-org/hs-miner-ng/pull/18
