### ISSUE TITLE
Auction closed with no bids

### ISSUE THREAD

**Issue by dylanbathurst** [handshake-org/hsd#53]
After opening an auction but not bidding on it during the bidding period, the auction is now closed, and  seems unable to be opened again. Do we have to wait the 27 days until it expires to reopen it?

`> hsw-rpc getnameinfo alicepaysbob`
```
{
  "name": "alicepaysbob",
  "nameHash": "3d61e5b16e22c646df9c993a73eba63a9c9c5463feeced11d5915e7d944ea5e8",
  "state": "CLOSED",
  "height": 7192,
  "renewal": 7192,
  "owner": {
    "hash": "0000000000000000000000000000000000000000000000000000000000000000",
    "index": 4294967295
  },
  "value": 0,
  "highest": 0,
  "data": "",
  "transfer": 0,
  "revoked": 0,
  "claimed": false,
  "weak": false,
  "stats": {
    "renewalPeriodStart": 7192,
    "renewalPeriodEnd": 15832,
    "blocksUntilExpire": 7366,
    "daysUntilExpire": 25.58
  }
}
```
`> hsw-rpc getauctioninfo alicepaysbob`
```
{
  "name": "alicepaysbob",
  "nameHash": "3d61e5b16e22c646df9c993a73eba63a9c9c5463feeced11d5915e7d944ea5e8",
  "state": "CLOSED",
  "height": 7192,
  "renewal": 7192,
  "owner": {
    "hash": "0000000000000000000000000000000000000000000000000000000000000000",
    "index": 4294967295
  },
  "value": 0,
  "highest": 0,
  "data": "",
  "transfer": 0,
  "revoked": 0,
  "claimed": false,
  "weak": false,
  "stats": {
    "renewalPeriodStart": 7192,
    "renewalPeriodEnd": 15832,
    "blocksUntilExpire": 7366,
    "daysUntilExpire": 25.58
  },
  "bids": [],
  "reveals": []
}
```

`> hsw-rpc sendopen alicepaysbob`
`Already sent an open for: alicepaysbob.`

`> hsw-rpc sendbid alicepaysbob 0.00001 0.00001`
`Name has not reached the bidding phase yet.`

**Comment by chjj** [comment]
```
> hsw-rpc sendopen alicepaysbob
Already sent an open for: alicepaysbob.
```

This is actually a bug in the wallet. It won't unindex opens after an auction has expired. I think we'll make this nicer on the consensus layer for testnet3 by allowing duplicate opens which don't affect namestate. That way the wallet has less bookkeeping to do and won't run into these issues.

**Comment by tynes** [comment]
@chjj Is this ok to close?
