### ISSUE TITLE
POST /wallet/:id/reveal will return 'Not found' when no name in params

### ISSUE THREAD

**Issue by peipeiTu** [handshake-org/hsd#530]
https://github.com/handshake-org/hsd/blob/a1409dc48b41b6f23d389d9448ecbde551502688/lib/wallet/http.js#L1079

I just found it not worked to post POST /wallet/:id/reveal will return 'Not found' when no name in params.
It seems fine when changing into  `return res.json(200, tx.getJSON(this.network));`

**Comment by pinheadmz** [comment]
Good catch thank you!

Confirmed this issue:

```
--> curl http://127.0.0.1:14039/wallet/primary/reveal -X POST
{
  "error": {
    "message": "Not found."
  }
}
```

and as you say, it is not an issue if a `name` is provided:

```
--> curl http://127.0.0.1:14039/wallet/primary/reveal -X POST --data '{"name":"test-txt"}'
{
  "hash": "6d12ab7bd0a50ba3d60b1d5a6646b4850d6d15163ad3262598827cd74b9cda5a",
  "witnessHash": "3b3ce8e3660c7579c495a4413bf4052d90127eec02cc7d3fc43593ac759a6c22",
  "mtime": 1610032618,
  "version": 0,
  "inputs": [
  ...
```

@peipeiTu are you interested/available to open a quick pull request for this fix?

If you really wanna go for the A+ you could add a test as well to this file:
https://github.com/handshake-org/hsd/blob/master/test/wallet-http-test.js

**Comment by peipeiTu** [comment]
Ok, I will try my best!
