### ISSUE TITLE
Review the DNS seeds for mainnet

### ISSUE THREAD

**Issue by Falci** [handshake-org/hsd#540]
https://github.com/handshake-org/hsd/blob/c85d9b4c743a9e1c9577d840e1bd20dee33473d3/lib/protocol/networks.js#L51-L54

It seems like `hs-mainnet.bcoin.ninja` is not resolving.
While `seed.easyhandshake.com` resolves

**Comment by Anunayj** [comment]
This does not seem to be a issue anymore? I just ran:
```
$ dig hs-mainnet.bcoin.ninja +short
50.112.123.184
54.184.104.94
47.240.14.207
149.129.80.119
8.209.83.152
39.104.16.90
64.227.15.172
173.255.209.126
138.197.212.176
165.227.15.245
108.178.131.118
39.106.221.130
172.104.214.189
40.113.229.250
8.131.238.19
45.79.134.225
172.104.177.177
39.106.215.11
39.106.223.166
165.22.151.242
139.162.183.168
44.229.138.206
```

**Comment by rithvikvibhu** [comment]
Hm weird. Looks like a problem with https://hdns.io, not hsd.

Works: `dig @1.1.1.1 hs-mainnet.bcoin.ninja`
Works: hsd full node rs
Doesn't work (SERVFAIL): `dig @103.196.38.38 hs-mainnet.bcoin.ninja`

**Comment by Anunayj** [comment]
Also hs-mainnet.bcoin.ninja does not seem to be signed with DNSSEC, I think that'd be nice to have.

**Comment by pinheadmz** [comment]
PR to restore easyhandshake is up for review: https://github.com/handshake-org/hsd/pull/599
