### ISSUE TITLE
Failed to install hsd on win10

### ISSUE THREAD

**Issue by aulyxair** [handshake-org/hsd#542]
Hi, I have some troubles installing hsd.
Here is what has been installed before: 
Latest Node.js
Visual studio 2019 with required C++ addons

Then I did:
>npm install -g node-gyp
>npm install --global windows-build-tools
>npm config set msvs_version 2017
>npm config set python C:/Python27
>git clone git://github.com/handshake-org/hsd.git
>cd hsd

then what I tried is to configure hsd:
>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.15.4 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\xxx\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2019 (16.8.30907.101) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\xxx\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Windows\\System32\\hsd\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xxx\\AppData\\Local\\node-gyp\\Cache\\14.15.4\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xxx\\AppData\\Local\\node-gyp\\Cache\\14.15.4',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\xxx\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.15.4\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Windows\\System32\\hsd',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Windows\\System32\\hsd\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\Windows\System32\hsd) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\xxx\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Windows\System32\hsd
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok

after trying 
>npm install --production
got the same error
gyp: binding.gyp not found (cwd: C:\Windows\System32\hsd) while trying to load binding.gyp
After playing with VS2017 I got some other result - binding.gyp was found, but was not valid:
`\AppData\Roaming\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 248, in LoadOneBuildFile
    build_file_data = eval(build_file_contents, {"__builtins__": {}}, None)
  File "binding.gyp", line 1
    browser/hsd*
               ^
SyntaxError: invalid syntax

What did I do wrong? Need help.
Thanks

**Comment by pinheadmz** [comment]
@tuxcanfly is usually pretty good at debugging Windows issues

**Comment by aulyxair** [comment]
Found how to solve the problem, hope it could help someone as well
**npm install -g https://github.com/handshake-org/hsd.git** 
Now it is downloading the blockchain, I will update when will see it is completely working

**Comment by tuxcanfly** [comment]
Great to hear that. I would do a root cause analysis for the git clone build but unfortunately I'm not maintaining my test windows installation any more. We should probably move to `gpk` and `git` for installs anyway. @aulyxair feel free to close if this is resolved.
