### ISSUE TITLE
Documentation around wallet confs

### ISSUE THREAD

**Issue by bucko13** [handshake-org/hsd#55]
Could not get certain configurations down to the wallet plugin. Took me a while but realized it was because wallet/plugin.js looks for `hsw.conf` not `wallet.conf` like in bcoin.

**Comment by boymanjor** [comment]
A guide from the `bcoin` docs modified for `hsd` has been posted here: https://handshake-org.github.io/guides/config.html

Once I merge an update to the readme which points to the documentation site I will close this issue.

**Comment by boymanjor** [comment]
This PR was merged: https://github.com/handshake-org/hsd/pull/57

I am closing this now.
