### ISSUE TITLE
[PROPOSAL] Decentralized Name Exchange on Handshake

### ISSUE THREAD

**Issue by kurumiimari** [handshake-org/hsd#550]
Greetings! I'm here today to propose some protocol changes that will enable decentralized name exchange natively on Handshake.

## Background

Currently, a Handshake name can only be transferred to an address known in advance. This is not ideal for exchange use cases, as settlement requires coordination between a specific buyer and seller. Ideally, name owners would be able to post fee-for-transfer transactions which could be redeemed by anyone who funds them with the requested amount of HNS. This would enable the trading of names without any intermediary.

## Proposed Changes

Create a new covenant called `RELEASE`. The `RELEASE` covenant contains the following fields:

- The name.
- The name's hash.
- A block height.

Spending the `RELEASE` covenant within the first 48 hours anywhere except to an `UPDATE` or `REVOKE` covenant is blocked. This is identical to how `TRANSFER`s work today.

Once the 48 hours are up, the owner of the name can create pre-signed transactions that authorize the spending of the `RELEASE` covenant. These transactions are very similar to the atomic name swaps implemented by @pinheadmz in the [Bob Wallet](https://github.com/kyokan/bob-wallet). They work like this:

1. Alice creates a transaction with the following properties:
	- She adds an input spending the `RELEASE` covenant.
	- She adds an output crediting herself some amount of HNS.
	- She signs the transaction using `SIGHASH_SINGLE | SIGHASH_ANYONECANPAY`. (It may require `SIGHASH_SINGLEREVERSE` depending on the final order of outputs, but this is trivial to change.)
2. Alice posts this transaction publicly.
3. Bob sees Alice's transaction, and adds the following to it:
	- He adds input funding Alice's HNS output.
	- He adds output that uses a `FINALIZE` covenant transfer the name in Alice's `RELEASE` covenant to himself.
	- He signs it using `SIGHASH_ALL`.
4. Bob broadcasts the transaction. Alice receives her money, and Bob receives his name.

In a market with multiple buyers for a single name, whoever broadcasts the transaction first wins.

There are several advantages to this approach:

1. It honors the 48-hour "cooling off" period that hinders unauthorized name transfers.
2. It allows names to be sold to any recipient non-interactively.
3. It requires no centralized intermediaries, as the pre-signed transactions can be hosted anywhere.
4. Transfers are atomic. All the seller can do is `REVOKE` or `UPDATE` the name once it is `RELEASE`d. They cannot grief buyers or cause them to lose funds.
5. When coupled with lock times, name owners can auction off their names in a reverse-Dutch auction style.

## My Ask

I'd love to hear feedback on the proposed changes, and determine if there's enough community interest to justify me implementing it. If there are better ways of achieving what I'm proposing here, please let me know and I'll go build that instead. I think it's critically important that we start decentralizing our marketplace/trading infrastructure: if Namebase is the only place to buy and sell Handshake names, we're no better than the legacy Web.

**Comment by pinheadmz** [comment]
I understand your use-case and I'm trying to wrap my head around the possibilities of implementing this. I think it may require a hard fork, which is not an easy thing to do unless the change is really, really critical to the survival of the project.

The main problem I think is that to change the `owner` of a name, a `FINALIZE` must be confirmed, and a `FINALIZE` can only be valid if a name has a `ns.transfer !== 0` value, which can only be set by a `TRANSFER` covenant. So I *think* it is impossible to add new covenants like `RELEASE -> FINALIZE` or even `RELEASE -> NEW_FINALIZE` without breaking backwards compatibility. But I could be wrong about this. Check it out yourself by reviewing the two consensus-critical functions in TWO separate modules:

`lib/covenants/rules.js: verifyCovenants()` checks the covenants being spent as INPUTS to a transaction.

`lib/blockchain/chain.js: verifyCovenants()` checks the covenants being created as OUTPUTS in a transaction.

Yeah, two different functions with the same name :-/ oh well.

While hsd does have soft-fork ability to expand the covenant system, I think the "naming" covenants CLAIM through REVOKE form a tight loop. Adding new covenants by soft-fork would not be able to manipulate Urkel Tree data, but they could be used to add new consensus data structures on to Handshake (the way Segregated Witness does or Extension Blocks would have worked on Bitcoin).

In the meantime, there is great work being done by @Falci on using HTLCs to enable non-interactive name sales. @tynes also has [this proposal](https://github.com/handshake-org/HIPs/pull/3) for non-interactive name swaps.

I encourage you to think more along the lines of what is currently valid on chain with current tools before considering protocol changes as an option. The atomic swaps you reference that already work and have been used on chain is already a super powerful tool that can relieve market pressure from Namebase's system. Sure it requires interaction but there are already forums popping up like http://handshake.mercenary where trades can be made.

There is also a wide-open possibility of using semi-custodial moderation (like OpenBazaar).

**Comment by Falci** [comment]
Hi @kurumiimari,

First of all, thanks for submitting this proposal.
Perhaps we could add to the [HIPs repo](https://github.com/handshake-org/hips).

**Comment by kurumiimari** [comment]
@pinheadmz:

Thanks for the in-depth response, I'll check out the `verifyCovenants` methods (both of them) and see if I can figure out a way to do this without breaking backwards-compatibility. My hunch though is that you are correct - this would require a hard fork. If hard forks are something the community is reserving for survival-critical changes, then this proposal is dead in the water.

I also took a look at @tyne's proposal for non-interactive swaps. His construction looks to be what I was looking for - will follow up on his PR with additional questions.

@falci:

In this proposal, the swap would happen with payment + `FINALIZE`, not release. I apologize if that wasn't clear. The full flow is:

1. Alice `RELEASE`s her name, broadcasts the pre-signed transaction, signs it with `SIGHASH_SINGLEREVERSE | SIGHASH_ANYONECANPAY`, and waits 48h.
2. Bob funds the pre-signed transaction, adds a `FINALIZE` output, signs it with `SIGHASH_ALL`, then broadcasts it. At this point, the name is irrevocably his and the money is irrevocably Alice's.

The critical difference between `TRANSFER` and `RELEASE` is that `RELEASE` does not require the recipient of the name to be committed to in advance. Since the money is transferred during the `FINALIZE` step, Bob's funds are never at risk. Note that this requires a change to the consensus rules around `FINALIZE` like @pinheadmz mentioned.

Do you have a link to the HTLC swaps work you are working on? Would love to learn more.

**Comment by pinheadmz** [comment]
I'll briefly summarize Falci's proposal. So, you still commit to an address in the TRANSFER but maybe it doesn't require a signature, it only requires the preimage to a hash. Then who ever wants to pay for the domain has to reveal the preimage.

So, by thinking "within the box" there is still a lot of interesting constructions possible.

**Comment by kurumiimari** [comment]
I've implemented the construction described in @tynes's HIP here: https://github.com/kurumiimari/shakedex. Will discuss more on the HIP itself.
