### ISSUE TITLE
Error npm install --production win 10

### ISSUE THREAD

**Issue by jmkl** [handshake-org/hsd#551]
Erroring out at this installation step.

Command
$ npm install --production

c:\program files (x86)\microsoft visual studio\2017\buildtools\hsd-2.3.0\hsd\node_modules\unbound\src\node_unbound.c(13
): fatal error C1083: Cannot open include file: 'unbound.h': No such file or directory [C:\Program Files (x86)\Microsof
t Visual Studio\2017\BuildTools\hsd-2.3.0\hsd\node_modules\unbound\build\node_unbound.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\hsd-2.3.0\hsd\node_modules\unbound
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by pinheadmz** [comment]
`unbound` is optional, hsd should still run fine without it.

https://github.com/handshake-org/hsd#unbound-support
