### ISSUE TITLE
LevelDB doesn’t seem to play nicely with node v14.16.0

### ISSUE THREAD

**Issue by williamjohnstone** [handshake-org/hsd#568]
While troubleshooting an issue with Bob wallet earlier today I and @pinheadmz discovered that there was a possible issue with LevelDB and node v14.16.0, I was running this inside Debian WSL on windows 10. I haven't done any additional debugging but I'll leave a screen shot of the error below.

![image](https://user-images.githubusercontent.com/37273113/109585508-8f085500-7afb-11eb-9e09-b7464bb12135.png)

**Comment by pinheadmz** [comment]
If possible I'd like you to explore the write permissions the hsd process has inside the Linux VM, could be as simple as that.
