### ISSUE TITLE
Redeem all via curl

### ISSUE THREAD

**Issue by befranz** [handshake-org/hsd#586]
I try to **redeem all** via curl which should work by passing null as name, but whatever I try (also omit name, name as empty string) I get error "No passphrase." Redeeming single names works fine. 

curl http://x:7cc6fba603b1740d03bb43e14f7005e4cd0b8fff@127.0.0.1:12039/wallet/bob1/redeem -X POST --data '{"passphrase":"mypwd","name":null,"broadcast":true,"sign":true}'

{
  "error": {
    "message": "No passphrase."
  }
}

hsd 2.4.0

Additional info:
Like @pinheadmz suggested sending an unlock tx beforehand circumvents this issue.

**Comment by pinheadmz** [comment]
Good catch, thanks. Check it out here in the code -- we aren't sending any `options` (including `passphrase`) to the `sendRedeemAll()` function! Should be an easy fix but I'll add some tests as well...

https://github.com/handshake-org/hsd/blob/9f0361f7e5b0bf0d2de6879c4d149991a45aab32/lib/wallet/http.js#L1163-L1174
