### ISSUE TITLE
Claiming Names

### ISSUE THREAD

**Issue by andrerfneves** [handshake-org/hsd#59]
Are claimed names on `testnet` going to be ported over to `mainnet` when it launches? Essentially, if I claim a name in an auction bid, win it, and thus have the rights to it on `testnet`, when `mainnet` launches, will that still hold true? Just going through all the docs now, so if this is answered elsewhere please disregard and point me that way! Cheers

**Comment by boymanjor** [comment]
Hello there! The state of the blockchain will be reset upon `mainnet` launch. `testnet` name registrations will not carry over to `mainnet`.

Just a heads up, we prefer to use GitHub issues for issues with the software. Questions like these are probably more apt for the irc channel: #handshake or unofficial Telegram group: https://t.me/handshake_hns

Thanks for checking out the project!
