### ISSUE TITLE
node crashes on Athlon

### ISSUE THREAD

**Issue by PeterMalkin** [handshake-org/hsd#60]
Illegal instruction on Athlon, same code works fine on Xeon.

$ ./bin/hsd
[info] (chain) Chain is loading.
[info] (chain) Checkpoints are enabled.
[info] (chaindb) Opening ChainDB...
Illegal instruction (core dumped)

$ cat /proc/cpuinfo
processor : 0
vendor_id : AuthenticAMD
cpu family : 16
model : 6
model name : AMD Athlon(tm) II X2 270 Processor
stepping : 3
microcode : 0x10000c8
cpu MHz : 800.000
cache size : 1024 KB
physical id : 0
siblings : 2
core id : 0
cpu cores : 2
apicid : 0
initial apicid : 0
fpu : yes
fpu_exception : yes
cpuid level : 5
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs : tlb_mmatch fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2
bogomips : 6800.26
TLB size : 1024 4K pages
clflush size : 64
cache_alignment : 64
address sizes : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor : 1
vendor_id : AuthenticAMD
cpu family : 16
model : 6
model name : AMD Athlon(tm) II X2 270 Processor
stepping : 3
microcode : 0x10000c8
cpu MHz : 800.000
cache size : 1024 KB
physical id : 0
siblings : 2
core id : 1
cpu cores : 2
apicid : 1
initial apicid : 1
fpu : yes
fpu_exception : yes
cpuid level : 5
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs : tlb_mmatch fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2
bogomips : 6800.26
TLB size : 1024 4K pages
clflush size : 64
cache_alignment : 64
address sizes : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

**Comment by chjj** [comment]
> [info] (chaindb) Opening ChainDB...
> Illegal instruction (core dumped)

Do you know which C standard library your OS is using? Alpine Linux is known to have issues with the latest leveldb due to its usage of a stripped down c std lib. I figure anything using that will probably have leveldb issues.

Not sure. I think @BluSyn has looked into this more.

**Comment by PeterMalkin** [comment]
Nah, this is vanilla Ubuntu 18.10. The machine is an AMD Athlon. Same code with same OS works fine on another machine I have that has Xeon.

**Comment by nartes** [comment]
There's definitely some problem. I experience a crash during `npm test`. The processor is AMD e-450. I tried to look into coredump. The crash happens bcrypto. But I'd need to recompile some modules with de ug symbols to say precisely what's causing a crash.

I've built an upstream on Archlinux.

**Comment by nartes** [comment]
*near bcrypo

**Comment by nartes** [comment]
*near bcrypto

**Comment by pinheadmz** [comment]
@PeterMalkin @nartes Sorry it's been a long time since this issue was addressed. Would it be possible to get an update? Lots of code has been updated since this was opened :-)

**Comment by PeterMalkin** [comment]
Since there was no updates here, I lost interest in the project and moved on. Closing this.
