### ISSUE TITLE
binary files collision with hs-client

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [handshake-org/hsd#638]
`hsw-cli` and `hsd-cli` are provided by both `hsd` and `hs-client` so I can't install them globally toghether

**Comment by pinheadmz** [comment]
You do not need to install them both. hsd requires and includes hs-client and the bin files from hsd are aliases and equivalent to the bin files from hs-client.

**Comment by Alessandro-Barbieri** [comment]
Thanks, good to know
