### ISSUE TITLE
Extend name claim period

### ISSUE THREAD

**Issue by Falci** [handshake-org/hsd#645]
Alexa top 100k, ICANN's TLD and any other reserved names are available for claim in a 4 years window. Ending in February 2024.

https://github.com/handshake-org/hsd/blob/72892ccc1700b2ed55966abef3bc7eb70e73a080/lib/protocol/networks.js#L307-L313

Simple and direct: **should we extend the name claim period?**

Keep in mind this would be a **hard fork!**

* Should we discuss it now or closer to the dead line?
* What should be the extended time?
* What's the impact of such change?
* What would be the process to apply this change?

I'd like to hear the community opinion.
(I'll add my opinion in a separated comment later)

**Comment by sebastianrasor** [comment]
I think that if we are to hard fork, it's better to do it sooner rather than later. That being said, I think there is value to extending the reservations. @pinheadmz makes a great point about how we shouldn't hard fork often, I agree that we should definitely try to compile everything that we have seen as a problem or foresee being a problem to avoid difficulties in the future. Back to the name claim period itself, I'd hate for Handshake to take off in the future and have to tell large players "well you should have got here earlier." 
Would there be any way to measure the "popularity" of Handshake on chain so we don't have to worry about if the arbitrary amount of time we choose is enough?

**Comment by NetOperatorWibby** [comment]
I think almost a decade as adequate reservation time, even by ICANN's glacier-like pace.

At that point I think it's _definitely_ fair to say "well you should have got here earlier."

Another perk of extending the reservation time is signaling to the community/outsiders that we're not in this to simply squat on brand names, make a quick buck, steamroll Web 2.0 with an idealized DNS, &c. We're signaling fairness (outside of "someone sniped my 1 HNS bid!") and our intention of longevity.

**Comment by nickrattus** [comment]
Agree with Paul. I am not technically qualified so can't comment on those aspects short of wanting the least risky approach. Macro wise this is a marathon not a sprint and we need to be diplomatic/ fair and firm.

**Comment by pinheadmz** [comment]
We can introduce some creativity into the new reserved claim rules, as well. For example, there are [flags](https://github.com/handshake-org/hsd/blob/27745128b3d8f5dd72b4cfbc933e14a1029dbe18/lib/covenants/reserved.js#L91-L94) in the code that identify reserved names as ICANN TLDs, alexa top 100 (the top of the alexa 100,000), and the "custom" names like `icann` itself. 

The hard fork rules can be applied differently to these groups, for example the ICANN TLDs can be _permanently reserved_ (See https://github.com/handshake-org/hsd/issues/294 and https://github.com/handshake-org/hsd/pull/256). 

I might even like to see a rule where the "ordinary" alexa 100k names (that are not top 100) are still released on schedule at the four year mark -- but we could even put those ~80,000 names on _another 52-week rollout_.

Just food for thought. The simplest and safest thing is changing a 4 to an 8, but we can also get more creative with it.

**Comment by rithvikvibhu** [comment]
I like the extension from 4 to 8 years.

Permanent reservation for ICANN TLDs might be convenient, but imo there needs to be _some_ pressure to claim them. If in 8 years we still have problems with getting registries to claim them, then we'll still have options:
- Handshake has significant in-use domains and can stick with the current plan of dealing with conflicts at the resolver level
- Extend the claim period again (unlikely, but can't predict what's going to happen in a decade).

---

For other things to include in the hard fork, maybe we could consider doing something about the ICANN TLD conflicts.

In case of existing conflicts like `.music`, `.kids`, Amazon's IDN TLD, they can be added to the reserved list and the owner (if there is one) gets back the burned HNS. This should be possible with hard forks, right?
If not, they can be added to the blacklist -- currently only the holdmyhand plugin stops them from resolving, but the name still exists on HNS. Getting them into hsd would cover a lot more surface.

Upcoming ICANN TLDs in review can also be added as they are likely to be accepted in 8 years. Even if they don't get approved, the Handshake names will be available once the claim period ends.

**Comment by FistFullOfAss** [comment]
Am all for the extra 4 year extension for people to claim their names. I see it as a nice gesture from the community extending an olive branch saying that we really do want you to claim your name and not for some anon to squat on it. It took Bitcoin about 7 years to get it's first big spotlight in the mainstream, so giving 8 years with the rate of adoption from traditional domainers seems like more than enough time to hop on the ride. Am curious to see what other small changes people will want to include in the fork. Would be cool to see a 52 week roll out for every name unclaimed, gives people even more time to claim their names and fair chance for everyone to have a chance at getting an unclaimed name.

**Comment by Falci** [comment]
> what else do we wanna hard fork?

Are you referring to developer claims?
If so, I would avoid merging both proposals because it would force the community to accept or reject both together, with no option to accept just one and reject the other.

**Comment by pinheadmz** [comment]
@Falci sorry I hit the wrong button 😬

I was referring to any of the hard fork proposals from the community over the last year. Funding development from miner subsidies, shortening the auction life cycle, even "he who opens an auction gets to bid last" etc

**Comment by befranz** [comment]
I think extending the claim period - and this better sooner than later - would be a good move. Having the option to set different rules for ICANN TLDs, Alexa 100k and other reserved names would even make it possible to avoid future naming conflicts (with few exeptions) but still encourage legacy name holders to claim with rules like this:
1. Extend claim period for all reserved names (to 8 years?)
2. All but ICANN TLDs will be open for auction if not claimed within (1.)
3. ICANN TLDs are reserved forever to claim but HNS can only be claimed within (1.)

**Comment by pgs0** [comment]
> @Falci sorry I hit the wrong button 😬
> 
> I was referring to any of the hard fork proposals from the community over the last year. Funding development from miner subsidies, SLDs on chain, shortening the auction life cycle, even "he who opens an auction gets to bid last" etc

I think slds on Chain would be a great additon as an alternative to the namebase staking program and taking a decentralized route. I mean the current program is just falsely advertised as decentralized

**Comment by Falci** [comment]
Another idea: reward halving.

This could be applied to all kinds of reward:
* Alexa 100k name claim
* ICANN TLD claim
* Developer claim

It is already applied to block rewards:
https://github.com/handshake-org/hsd/blob/56c83ca7344def512ef861f452bff91d43bc8f52/lib/protocol/networks.js#L92-L99
(Never happened but it is already in the consensus rules)

To make it simple, we could use the same values: 50% less every 170000 blocks.

> As long as 100% of the network upgrades to at least v3.0.0 sometime in the next 2.5 years, we will effectively hard fork the protocol with essentially 0 impact.

Note the halving will happen sooner (around April of 2023)

**Comment by dnsguru** [comment]
Extending the claim period is a good and responsibile idea to put in place, +4 years, +10 years, +25 years, whatever the term is.  The downside is that it might diminish the urgency to act which may have had some claim sooner vs defer, but the upside is that Handshake can be seen as a mature and trustable platform.

There are TLDs that should have been set aside as ICANN TLDs that either:
* went to auction and were acquired (ex: .music, .spa, hotels etc);  or,
* were placed in the alexa list instead of the ICANN list (ex: .web etc)

There are also some TLDs (mostly .brand that opted to later not launch) which were in the ICANN root which have been released and could be available in Handshake (ex: .active, .blanco, .boots etc) (see: [ICANN gTLDs JSON Report](https://www.icann.org/resources/registries/gtlds/v2/gtlds.json), constantly updated) 

 It would be good to use this hard fork to address where some TLDs were missed and went to auction - we've discussed this and it seems a bit controversial but the mistakes that let some errors slip through should be fixed.  It is problematic and it creates more difficulty in having conversations with large providers to describe that there is name collision now as opposed to it being something to address later for names that have auctioned (.music, .spa, hotels etc).

**Comment by smcki012** [comment]
I would agree that a solid bundled upgrade would consist of the parameter bump, and the clean-up of ICANN reserved names so we can continue as we have, successfully, with less concern over those narratives (which is really one of the few I've seen publicly). If we're going to push that timespan back, it would make sense to do all we can to lessen objections from incumbent in the current DNS space. 

Then you just brand the hard fork upgrade, and it's more easily digestible. I.E the "Wecann" update, that extends claim time for ICANN and clears up any minor backwards incompatibilities that were missed. It's sensible, easy to grok quickly, and isn't make anyone uncomfortable with the scope of changes. 

This is human psychology: you need to establish trust by doing small things before you can make larger sweeping changes to the globes new universal namespace. Show you can deploy a *simple* hardfork upgrade and go from there.

**Comment by pinheadmz** [comment]
@dnsguru 

> there's loads of public information to support this.

I would like to see the public information that supports your accusation that the founders' design was negligent or ignorant or a mistake.

The public information that I can see is:

- A bunch of Handshake code that relies explicitly on DNSSEC signatures by ICANN
- A list of names signed by ICANN

The public information I do NOT see is:

- A verifiable signature by ICANN for the name .music in [the IANA root zone](https://www.internic.net/domain/root.zone)

**Comment by faltrum** [comment]
I'm in favor to extend the period to 8 years to facilitate the adoption. I'm against to include more TLD in Alexa 100k. Thnks

**Comment by hnshnshnshns** [comment]
Most of the names that haven't been claimed are of high value to web 2. if they know about hns, that would be a big deal, put blockchain domain names get more practical.

mainly with the claimed names, it made the web2 domain auction community attracted by hns, domain name speculators, etc., they are quite important to the domain name ecosystem. cocacola , pepsi, they all love web3, web 3 domain, but they still don't know they can claim their rewards.

I like how Balaji looks at HNS, an ID. a company like tesla might have bob's employee profile at bob.tesla , or if twitter claims their domain, something big will happen...
