### ISSUE TITLE
Non-custodial name purchase initiated by buyer?

### ISSUE THREAD

**Issue by befranz** [handshake-org/hsd#680]
Is there a way to create a non-custodial, time-limited binding offer to have a trustless alternative secondary market initiated by buyers?
If so, I imagine existing platforms like niami, sinpapeles and nameboard could evolve to trustless alternatives to namebase.

In case step 1 is possible, I think of a workflow like so:
1. Potential buyer deposits purchase price to own address and creates presigned time-limited tx to transfer amount to current name address if deposit address is - then - name owner, at the same time it's time-locked to be moved to another address
2. Potential buyer posts presigned tx on marketplace or sends to seller
3. Current name owner checks if and how long presigned tx is valid for his name
4. If 3. ok, name owner starts transfer and after 288 blocks he/she executes finalize and presigned tx.

**Comment by pinheadmz** [comment]
This would probably be a better discussion in HIPs than an hsd issue. Be sure to check out the comments in https://github.com/handshake-org/HIPs/discussions/27 as well. As I mentioned on Telegram a sort of atomic swap may be possible:

Interested buyer constructs this partially signed TX and sends to name owner (somehow...)


| index | Inputs | Outputs |
|-|-|-|
| 0 | (empty) | FINALIZE to buyer's address with desired name committed in covenant |
| 1 | Buyer's UTXO with exact amount of offer price (no change is possible) sighash SINGLEREVERSE+ANYONECANPAY | (empty) |


Name owner sends TRANSFER of name to buyer's address (no HIP-1 locking script is required). As long as the buyer's UTXO in input 1 is still available 288 blocks later, the final step is valid: Name owner fills in the rest of the TX:


| index | Inputs | Outputs |
|-|-|-|
| 0 | TRANSFER UTXO committing to buyer's address sighash ALL | FINALIZE to buyer's address with desired name committed in covenant |
| 1 | Buyer's UTXO with exact amount of offer price (no change is possible) sighash SINGLEREVERSE+ANYONECANPAY | Name owner's receive address for payment (minus miner fee) |
