### ISSUE TITLE
How do I create transaction offline?

### ISSUE THREAD

**Issue by ygcool** [handshake-org/hsd#704]
install:
```
npm install -g https://github.com/handshake-org/hsd.git
```

Generate private keys and addresses offline:
```
const Keyring = require('hsd/lib/primitives/keyring.js');
const key = Keyring.generate();
console.log(key.getAddress().toString());
console.log(key.toSecret("main"));
```

How do I sign a transaction using my private key?

Please give me an example if you can, thanks

**Comment by pinheadmz** [comment]
https://hsd-dev.org/api-docs/#signrawtransaction

**Comment by ygcool** [comment]
> https://hsd-dev.org/api-docs/#signrawtransaction

Sorry, I can't build hsd nodes. I need to use javascript code for transaction building and signing with private key.

like bitcoin.js example:
```
const bitcoin = require('bitcoinjs-lib');
const testnet = bitcoin.networks.testnet
const keyPair = bitcoin.ECPair.fromWIF('wif private key', testnet);

const txb = new bitcoin.TransactionBuilder();

txb.addInput('61d520ccb74288c96bc1a2b20ea1c0d5a704776dd0164a396efec3ea7040349d', 0);

txb.addOutput('1cMh228HTCiwS8ZsaakH8A8wze1JR5ZsP', 12000);

// sign
txb.sign(0, keyPair);
// Get the hex data needed for the broadcast transaction
console.log(txb.build().toHex());
```

**Comment by Anunayj** [comment]
If you look into closely at lib/primitives/mtx.js https://github.com/handshake-org/hsd/blob/107ed2be9280bb4292d21330e7d1ace62da9a002/lib/primitives/mtx.js#L879-L887 , you'd quickly find equivalent methods to everything there.

So the hsd equivalent of this would be

```js
const MTX = require('../lib/primitives/mtx');

const keyring ... // However you get it, but must be able to spend the outpoint(s)
const mtx = new MTX();
// Add Input
mtx.addOutpoint({
  hash: Buffer.from("61d520ccb74288c96bc1a2b20ea1c0d5a704776dd0164a396efec3ea7040349d","hex"),
  index: 0
})
mtx.addOutput(new Output({
  value: 12000,
  address: new Address("hs1qsp77a07wkn6caeel4w44ktjdpufy8sgkknm0sp") // I think this should work, didn't test
}));

mtx.sign(keyring)
mtx.toTX()
```

**Comment by ygcool** [comment]
> If you look into closely at lib/primitives/mtx.js
> 
> https://github.com/handshake-org/hsd/blob/107ed2be9280bb4292d21330e7d1ace62da9a002/lib/primitives/mtx.js#L879-L887
> 
> you'd quickly find equivalent methods to everything there.
> 
> So the hsd equivalent of this would be
> 
> ```js
> const MTX = require('../lib/primitives/mtx');
> 
> const keyring ... // However you get it, but must be able to spend the outpoint(s)
> const mtx = new MTX();
> // Add Input
> mtx.addOutpoint({
>   hash: Buffer.from("61d520ccb74288c96bc1a2b20ea1c0d5a704776dd0164a396efec3ea7040349d","hex"),
>   index: 0
> })
> mtx.addOutput(new Output({
>   value: 12000,
>   address: new Address("hs1qsp77a07wkn6caeel4w44ktjdpufy8sgkknm0sp") // I think this should work, didn't test
> }));
> 
> mtx.sign(keyring)
> mtx.toTX()
> ```

thanks.
Maybe something is missing? Transactions are not broadcast properly after doing this
```
mtx.encode().toString("hex")
```

get data like this:
000000000177754c20b109bc05686c0787a158f5e728d9d477ef64f59220653a9439bb8fef00000000ffffffff021027000000000000001489f87167b4130e13292729bf1a69e35d19cb33e60000ac6efa01000000000014f74ae2d5c4cb4ea6d50e0983797653c93d4de11c00000000000000

Then,  post url:  http://x:api-key@127.0.0.1:14037/broadcast
return 500.

**Comment by Anunayj** [comment]
Oh right you will have to add the Coin to the view, because right mtx.sign() doesn't know about the outpoint's value and script.
You can use something like
```js
mtx.addCoin(new Coin().fromTX(prevtx))
```
instead
