### ISSUE TITLE
bad-claim-time

### ISSUE THREAD

**Issue by builtwith** [handshake-org/hsd#717]
I am trying to claim a Alexa 100k domain - I've got DNSSEC and TXT record setup but I'm getting 

`Verification failure: bad-claim-time`

I've found the code for it -

`if (tip.time < data.inception || tip.time > data.expiration) throw new VerifyError(claim, 'invalid', 'bad-claim-time', 10);`

in mempool.js but I cannot figure out what is causing it can anyone help?

**Comment by pinheadmz** [comment]
The "bad time" here refers to the RRSIGs in your DNSSEC chain.

Here's one quick example:

```
--> dig torproject.com rrsig +short
DNSKEY 8 2 3600 20220603154234 20220424150211 28383 torproject.com. PKUO9B1UhURlmoseFvJYEc0KuERpHvgtkwStqTXwQZxx+KifGu3Rwq7T yMhzLzjWRAjOfUsOU/IprIMVpptMQyV5UdbFonYEK+FRLBBY98kZf4qm isa7Anm2u1iI2bYcn/j306iqKMSd7dWwu/w3Z91+XksgPmUjncwZrWY1 G2jhaNuSbbSokfsk6UKLfanoJmzak4hw020D8yKThgjDQG3L4oFYHArJ vt/AsXzFS2//iEMtp/H9FMFIRbvnHg7s
```

This RRSIG has inception time of `20220424150211` (Apr 24, 2022) and expiration time of `20220603154234` (June 3, 2022)

If you want to provide the name you are trying to claim I can help debug further.

**Comment by builtwith** [comment]
Thanks it' builtwith (builtwith.com) - I don't appear to have RRSIG record I setup DNSSEC using Amazon Route 53 if that helps. Thank you for your help.

**Comment by builtwith** [comment]
Hi this appears to be working now thank you - maybe I was too quick on setting up DNSSEC and sending the claim.
