### ISSUE TITLE
request@2.12.0 deprecated

### ISSUE THREAD

**Issue by chrisschaub** [handshake-org/hsd#720]
Just a ticket to remind to remove request npm for native node approach, probably upgrade Docker to node:16 as well.

npm WARN deprecated request@2.12.0: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by nodech** [comment]
HSD does not use `request`.
It uses https://github.com/bcoin-org/brq/

**Comment by chrisschaub** [comment]
Hmm, ok. Saw this when building, maybe a remnant someplace. Thanks.
