### ISSUE TITLE
Value on Single Bid Names

### ISSUE THREAD

**Issue by kilpatty** [handshake-org/hsd#74]
If I call "getnameinfo" on a domain that was won with only 1 bid, value is always returning as 0 - was just checking to see if this is expected behavior. 

If so, I think it could potentially be helpful to return value === highest in the case of single bid domains.

**Comment by turbomaze** [comment]
Hmm. From testnet, it seems that in the case of a single bid, the bidder is able to recover all of their funds, essentially getting the domain for free. But on a closer look, it seems the whitepaper has changed to include the following:

```
Once the reveal period has ended, a winner is chosen. This winner is able to
redeem their `REVEAL` output to a `REGISTER` covenant. The `REGISTER` output
must have a value equal to the second highest bid, or in the case of only one
bid, the participant's own bid value.
```

I don't believe this is currently implemented in testnet2, unless you've noticed differently.

**Comment by boymanjor** [comment]
The white paper is stale. The winner of a single bid auction should retain all of their funds. I'm going to close this for now.
