### ISSUE TITLE
Error Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Nathanwoodburn** [handshake-org/hsd#740]
I'm running a Linux 22.04 LTS VM with 23GB of RAM and 45 GB storage
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        45G   28G   18G  62% /

               total        used        free      shared  buff/cache   available
Mem:            23Gi       730Mi       405Mi       1.0Mi        22Gi        22Gi
```
Node.js v12.22.9
HSD version 3.0.1

Installed HSD using [Build from source](https://github.com/handshake-org/hsd/blob/master/docs/install.md#building-from-source-git-and-npm) approx. a week ago

Running using
`./hsd --listen --public-host x.x.x.x --max-inbound 1000 --bip37 true --api-key=<API-KEY>`

![hsd error core dump](https://user-images.githubusercontent.com/62039630/173228842-19208264-67d0-4bd0-8bec-3702005a0cc3.png)

HSD Info
`{
  "version": "3.0.1",
  "network": "main",
  "chain": {
    "height": 124114,
    "tip": "0000000000000003b41628b12d7c53c1cfa33286fe165c2304d5611e8a26ccd9",
    "treeRoot": "3eaa91c8af99466bee37f586c5c170c0bc939d22a798a1b367c1b93f1e653dfa",
    "progress": 1,
    "state": {
      "tx": 6788347,
      "coin": 10739810,
      "value": 498625110678174,
      "burned": 26178384940983
    }
  },
  "pool": {
    "host": "152.69.185.197",
    "port": 12038,
    "brontideHost": "152.69.185.197",
    "brontidePort": 44806,
    "identitykey": "ap7q5svl2ylju4gok6z37ahbk234ojgi6tpbavarxhzvz6gm47bda",
    "agent": "/hsd:3.0.1/",
    "services": "11",
    "outbound": 8,
    "inbound": 1
  },
  "mempool": {
    "tx": 40,
    "size": 299216,
    "claims": 0,
    "airdrops": 0,
    "orphans": 0
  },
  "time": {
    "uptime": 174,
    "system": 1655029335,
    "adjusted": 1655029335,
    "offset": 0
  },
  "memory": {
    "total": 207,
    "jsHeap": 62,
    "jsHeapTotal": 64,
    "nativeHeap": 143,
    "external": 28
  }
}`

**Comment by pinheadmz** [comment]
Try upgrading to node 16 if you can and let us know if the problem persists

**Comment by Nathanwoodburn** [comment]
> Try upgrading to node 16 if you can and let us know if the problem persists 

Will do and get back to you

**Comment by Nathanwoodburn** [comment]
> Try upgrading to node 16 if you can and let us know if the problem persists 

Done and now it just dies straight away.

![Screenshot_20220612-210801.png](https://user-images.githubusercontent.com/62039630/173230213-4bf31c43-c5f4-43ce-80f7-ef24539096ff.png)

**Comment by nodech** [comment]
Are there any updates on this ?

It looks like the issue could be related to the system unbound version using different TLS version than Node.JS. But need more details. E.g. running npm test could provide that information (as Server Configuration -> Full Node should segfault)
