### ISSUE TITLE
Inconsistent wallet state after recovering from seed phrase

### ISSUE THREAD

**Issue by turbomaze** [handshake-org/hsd#75]
##### Description
I was testing recovering funds and names from a seed phrase and observed some strange behavior. Despite being able to manage names that I knew the wallet owned, 1) `hsw-cli rpc getnames` returned an empty list, and 2) `hsw-cli rpc getnameinfo XXX` returned a different response than `hsd-cli rpc getnameinfo XXX`. `hsd-cli` returned the correct name state (e.g. domain was in the BIDDING state), and `hsw-cli` returned an incorrect name state (e.g. domain was CLOSED).

##### Reproducing
Unfortunately I do not have a minimum example. But I will try to explain my steps in sufficient detail.

1. Acquire some funds and names on full node A (explicitly referring to the full node to emphasize starting from a fresh chain).
2. Check to see the names this wallet has interacted with: `hsw-cli rpc getnames` ==> nonempty.
3. On full node B, `hsw-cli mkwallet NAME --mnemonic "seed phrase"`.
4. Check the wallet's balance `hsw-cli --id NAME --account default get` ==> `0` as expected
5. Rescan the tx db `hsw-cli rescan 0` and wait for it to finish. (NOTE: is this all that's necessary to restore a wallet? If there are other necessary steps, then I did not do them)
6. Now check the wallet's balance `hsw-cli --id NAME --account default get` ==> the original amount from step 1, as expected.
7. Try to ask full node B for the names its wallet owns: `hsw-cli rpc getnames` ==> empty, unlike in  step 2.

I suspect this is related, but I also observed inconsistencies in running the following commands on full node B:
1. `hsw-cli rpc getnameinfo XXX` ==> reported XXX to be closed
2. `hsd-cli rpc getnameinfo XXX` ==> reported XXX to be bidding, the correct answer

##### Details
In the interest of providing as much helpful information as possible, I should also note that these full nodes contained a modified lookahead parameter (here: `./lib/wallet/account.js:53,836`) because the default value of 10 was insufficient for a full recovery. I would not expect this to lead to the issues I observed, but you never know.

I also tried recovering the wallet on totally clean, freshly sync'd full nodes and also full nodes that were already up-to-date and running for a while. Neither behaved as expected for the `getnames` rpc call, and I do not recall if both nodes returned inconsistent results for the `getnameinfo` calls or if it was just the freshly sync'd full node that had trouble.

**Comment by chjj** [comment]
Thanks for the writeup. I would say the wallet is definitely the hardest part of this whole project. Maintaining all that state locally with a limited view the network state is really difficult. So I'm not surprised it's behaving strangely.

> Rescan the tx db hsw-cli rescan 0 and wait for it to finish. (NOTE: is this all that's necessary to restore a wallet? If there are other necessary steps, then I did not do them)

So, one of the problems here is probably that the wallet is not _watching_ those names. When you send an open or a bid, the wallet adds that name to the watch list (so it can observe incoming bids/reveals from other parties).

I'll be looking into this more in a few days. We should figure out some better solution for this. Some kind of `watchname` RPC could might be necessary before a rescan.

**Comment by pinheadmz** [comment]
@turbomaze there's been a lot of updates since this issue was opened. I just tried a wallet recovery and rescan on simnet with a test wallet that has 6 names in various states and over 60 transactions. Everything was cool.

If possible could you give us an update? This issue might be close-able now.

**Comment by turbomaze** [comment]
I just attempted to recover a wallet with >1000 names on testnet4, and "getnames" returned the correct number of names. "get" returned a balance that was 10% off (probably related to the lookahead parameter, I have not checked). At least as far as this issue is concerned, I was not able to reproduce the issue with the steps outlined.

**Comment by pinheadmz** [comment]
Closing this for now, there are newer issue regarding wallet rescans and fixes are merged or in progress.
