### ISSUE TITLE
Node not syncing when missing data directories

### ISSUE THREAD

**Issue by rithvikvibhu** [handshake-org/hsd#754]
Seems like it breaks something silently, no errors anywhere.

- start node A and mine a few blocks
- start node B with A as peer, it syncs properly
- close node B and delete blocks,chain,tree
- start node B back again
- Now **node B chain is stuck at height 1** (as seen in hsd-cli info, and no connect events)

What's funny is the node actually asks for blocks, just doesn't update chain.

### Reproduce problem

Start node A:
```sh
hsd --prefix /tmp/hsd_1 --network regtest --no-dns --index-tx=true --index-address=true --no-wallet --listen --bip37 --log-level spam
```

generate blocks:
```
hsdgen 100 (or your alias)
```

Start node B:
```sh
hsd --prefix /tmp/hsd_2 --network regtest --no-dns --index-tx=true --index-address=true --listen --bip37 --port 14238 --http-port 14237 --brontide-port 45826 --wallet-http-port 14239 --only 127.0.0.1:14038
```

Watch B sync 100 blocks, then stop it.

Delete B's data:
```sh
cd /tmp/hsd_2/regtest
rm -rf blocks chain tree
```

Start B again (above)

See height doesn't go past 1 with:
```sh
HSD_HTTP_PORT=14237 hsd-cli info
```

Starting B again will sync properly, probably because those dirs are present this time).

### Logs

This is what Node B looks like when it doesn't download blocks:
![image](https://user-images.githubusercontent.com/5113343/176501655-7afa4066-1b56-4976-be6c-4f307dac7fc7.png)

When restarting, it starts syncing properly:
![image](https://user-images.githubusercontent.com/5113343/176501702-8384ebb7-e2d6-4c61-9526-ebcae78d7177.png)

Also noticed that both nodes say that the other has not responded to ping (when in the state where they don't sync). After a while they disconnect and connect again. They still do not sync (only killing and restarting hsd will start sync).

**Comment by pinheadmz** [comment]
Can't reproduce on OSX, node v16, hsd master at commit 999145ad1b03a366a8bc0fbff822b6cf738ecaf1

Will try linux next, do you have any other details or ideas what the issue might be ?

**Comment by pinheadmz** [comment]
Ok tried again on Ubuntu 20, followed your steps and the node synced fine.

**Comment by rithvikvibhu** [comment]
Huh, just tried it on latest code and there's no issue. Either it was an issue but fixed recently, or some change I had made that broke things, or some other problem with my local setup. Sorry, closing this now.
