### ISSUE TITLE
Chain.syncTree error – hsd doesn't start

### ISSUE THREAD

**Issue by handshake-enthusiast** [handshake-org/hsd#793]
`hsd` (version 5.0.0-rc.1) stopped working without a clear guidance how to fix.

Log:  
```
$ ./hsd/bin/hsd --no-wallet --prefix hsd_data/
[info] (blockstore) Opening FileBlockStore...
[info] (chain) Chain is loading.
[info] (chain) Checkpoints are enabled.
[info] (chaindb) Opening ChainDB...
[debug] (chain-migrations) There are no migrations pending. last id: 3
[debug] (chain-migrations) Last migration 3, last available migration: 3
[info] (chain-migrations) There are 0 migrations.
[info] (chaindb) ChainDB successfully loaded.
[info] (chaindb) Chain State: hash=00000000000000004299bc1f4494d678190fac05070e202e11c12d4ee1d26084 tx=8547490 coin=13503258 value=532458651.308212 burned=27898345.133312.
[info] (chaindb) Tree Root: f611a3db097f2c8f2e5b325c39d180f41eded1af8f16796650df06d0f1a7cc66.
[info] (chain) Chain Height: 140060
[debug] (chain) Memory: rss=97mb, js-heap=18/25mb native-heap=71mb
[info] (chain) Synchronizing Tree with block history...
AssertionError [ERR_ASSERTION]: Assertion failed.
    at Chain.syncTree (./hsd/lib/blockchain/chain.js:198:7)
    at async Chain.open (./hsd/lib/blockchain/chain.js:108:9)
    at async FullNode.open (./hsd/lib/node/fullnode.js:293:5)
    at async ./hsd/bin/node:75:3
```

`hsd.conf` contains:  
```
index-address: true
index-tx: true
```

**Comment by pinheadmz** [comment]
Hm that's a pretty critical error, there are blocks missing from the database. What else can you tell us? What version were you upgrading from? Is this a bob wallet instance? Do you know if you have pruned the chain or compacted the urkel tree?

For sanity also please check that you have adequate disk space and maybe even post some of the log from the *last* time you successfully ran hsd in this configuration

**Comment by handshake-enthusiast** [comment]
>What version were you upgrading from?

4.0.2

>Is this a bob wallet instance?

No, it's on Raspberry Pi which was working all the time, but may be some power outage happened.

>Do you know if you have pruned the chain or compacted the urkel tree?

I haven't done anything like that on purpose for sure.

**Comment by handshake-enthusiast** [comment]
>For sanity also please check that you have adequate disk space

I have enough disk space for sure.

>and maybe even post some of the log from the last time you successfully ran hsd in this configuration

Unfortunately, this `hsd` is normally running like a daemon (with `--daemon` setting), so there are no `debug` level logs like the last part:  
```
AssertionError [ERR_ASSERTION]: Assertion failed.
    at Chain.syncTree (./hsd/lib/blockchain/chain.js:198:7)
    at async Chain.open (./hsd/lib/blockchain/chain.js:108:9)
    at async FullNode.open (./hsd/lib/node/fullnode.js:293:5)
    at async ./hsd/bin/node:75:3
```

Here are [the latest logs](https://gist.github.com/handshake-enthusiast/f0352abe77e11f2649155004295daa8f).

**Comment by handshake-enthusiast** [comment]
>What else can you tell us?

May be some corruption was caused by a power outage because of harsh weather conditions yesterday. I haven't even noticed. As you can find in logs `[D:2023-01-11T11:32:20Z] (peer) Peer has not responded to ping (50.116.35.178:12038).` is the last entry for `2023-01-11`.

**Comment by handshake-enthusiast** [comment]
>so there are no debug level logs like the last part  

I may be technically incorrect here. As stated on https://hsd-dev.org/guides/config.html `log-level` is `debug` by default. Errors like are not in logs:  
```
AssertionError [ERR_ASSERTION]: Assertion failed.
    at Chain.syncTree (./hsd/lib/blockchain/chain.js:198:7)
    at async Chain.open (./hsd/lib/blockchain/chain.js:108:9)
    at async FullNode.open (./hsd/lib/node/fullnode.js:293:5)
    at async ./hsd/bin/node:75:3
    ```

**Comment by pinheadmz** [comment]
> latest logs

```
[D:2023-01-11T11:32:20Z] (peer) Peer has not responded to ping (50.116.35.178:12038).
[I:2023-01-12T07:29:21Z] (blockstore) Opening FileBlockStore...
```

Is this when the power went out?

**Comment by handshake-enthusiast** [comment]
>Is this when the power went out?  

Hm, as far as I remember – yes, likely, around that time there was a power outage for sure. I could also turn it off myself and forgot to turn it on. It should automatically be started on boot (and was normally automatically starting). As I see it tried to autostart early today, but I suppose it got that error and couldn't proceed.

**Comment by handshake-enthusiast** [comment]
>What kind of disk are you storing the hsd data on?

It's an external SSD.  

>USB3 external SSD for data

USB 2.0 in my case https://www.raspberrypi.com/products/raspberry-pi-3-model-b-plus/

**Comment by handshake-enthusiast** [comment]
>Since the v5 migration is wallet only and you are running without a wallet, you could try resetting back to hsd v4.0.2 and restarting. 

Same error with v4.0.2.

**Comment by handshake-enthusiast** [comment]
I remember having some problem when `hsd` didn't want to start which was resolved with deletion of some file like `chain/LOCK` instead of deleting the whole directories. May be this could be a solution here as well.

**Comment by pinheadmz** [comment]
That is a good indication that the last shutdown was not clean

**Comment by handshake-enthusiast** [comment]
Likely not the first time I get problem with "`hsd` doesn't start" because of something (power outage?) BTW. But the first time I haven't quickly found a solution and decided to report.

**Comment by handshake-enthusiast** [comment]
or if your reply is related to `chain/LOCK` then yes, most likely.

**Comment by handshake-enthusiast** [comment]
Let me know if there are any files that I can remove to fix the issue and continue running my node.

**Comment by pinheadmz** [comment]
You probably have to wipe out blocks chain and tree directories  and resync from genesis

**Comment by handshake-enthusiast** [comment]
Ouch, it will take many days to catch up 😬 Probably because of reindexing, or 1 GB RAM, or slow listening nodes, or latency, or all together...

**Comment by pinheadmz** [comment]
Yeah I know sorry. Depending on your use case you might be able to run hnsd instead

**Comment by nodech** [comment]
One trick that can be used is to remove `.hsd/blocks/index` directory, and restart the node. It will attempt to reindex blockstore metadata from the blockstore files.

But this still needs investigation, should not be happening.
PR https://github.com/handshake-org/hsd/pull/688 attempts to fix that, but there's some edge case I guess.
