### ISSUE TITLE
TX failed sanity check.

### ISSUE THREAD

**Issue by enginux** [handshake-org/hsd#801]
### Issues:
1. **Can't Finalize transfer**
2. **Can't Reveal "No Bids to reveal" and "Bid value not found"**

Note: Done with `./hsd --wallet-migrate=2`

**Comment by enginux** [comment]
This could be a problem when you have a pending transactions from old HSD version then migrate to a new version. 
A Consensus sanity checks: https://github.com/handshake-org/hsd/blob/66d9e3ca025c39ad076ce6972cdd55925ada0c7f/lib/wallet/wallet.js#L3955

**Comment by pinheadmz** [comment]
If anything, hsd v5 is preventing your wallet from broadcasting a transaction that will not be relayed across the network, and there are several reasons for this. We'd need some more details to figure out whats going on. What's the exact command you are executing in both cases (finalize and reveal).
