### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by wi-ski** [handshake-org/hsd#85]
This documentation page: https://handshake-org.github.io/guides/wallet.html

Has a typo! Ctrl+F: `"Seting up a Handshake Wallet"`

Ideally, would say: `"Setting up a Handshake Wallet"`

**Comment by boymanjor** [comment]
Thanks, this has been fixed. That said, this issue should have probably been added to the GitHub repo for the docs site here: https://github.com/handshake-org/handshake-org.github.io
