### ISSUE TITLE
Support generate only mode for transaction-creating RPC endpoints

### ISSUE THREAD

**Issue by mslipper** [handshake-org/hsd#89]
Hey there! I'm in the process of writing a client for @boymanjor's HNS Ledger app. One thing that would make the process significantly easier would be the addition of a generate-only mode for Wallet RPC endpoints that create transactions. Generate-only mode would make `hsd` return the bytecode for a valid transaction so that another entity (like a Ledger device) can sign and broadcast it via `sendrawtransaction`. Specifically, these RPC endpoints are in scope:

- sendopen
- sendbid
- sendreveal
- sendredeem
- sendupdate
- sendrenewal
- sendtransfer
- sendcancel
- sendfinalize
- sendrevoke
- senddtoaddress

I'd imagine that generate-only mode for each of the above would be invoked via a CLI flag such as `--generate-only`. For example: `hsw-rpc sendopen $name --generate-only`.

If there's interest, I'd be happy to implement this myself and provide a PR for review. The alternative right now is to manually generate transactions, which isn't ideal from a client development standpoint because every client will have to re-implement the same input selection and output creation logic.

The only downside I can see here is potential for 'orphaned' addresses to be generated. Consider the following flow:

1. I generate a `send` transaction. This requires the creation of a new receive address.
2. I don't sign the transaction.
3. The newly-generated receive address is dangling if the new receive address is persisted prior to generating the `send` transaction.

Would love to hear your thoughts on the above!

**Comment by mslipper** [comment]
Spoke with Boyma about this - a better solution would be to have mirror RPC endpoints like `createopen`, `createbid`, etc. I'll have a PR our for that shortly.

**Comment by tynes** [comment]
Closing this since it was merged here: https://github.com/handshake-org/hsd/commit/405aa767f51b9c029d16d61aed30fc6201b59e73

Feel free to reopen if that PR didn't address everything you need
