### ISSUE TITLE
new version  stuck on headers 

### ISSUE THREAD

**Issue by esmiwuals2** [handshake-org/hsd#909]
stuck on receiving 2000 headers.....endless loop
version 7.99.0 
height: 161043
0.633 % until full sync

**Comment by nodech** [comment]
Could you provide more details ?
What are the nodes configurations ?
  - is it full node/spv/pruned
  - does it have wallet
  - any errors in the log?

**Comment by esmiwuals2** [comment]
it is a full node , default wallet in place, log is attached, it works as far as i can tell , but it will not fully sycn like this , well not true it will, but slow, now the height is 161275, 233 block have sync in all this time
![newNode](https://github.com/user-attachments/assets/2d8b6da7-2455-4d97-a05f-f01f4d7804e1)

**Comment by nodech** [comment]
hm... try using different nodes to sync from ? (Restart, maybe remove hosts.json)

Did it sync before upgrade ? Or is this the fresh one on the latest ?

**Comment by esmiwuals2** [comment]
fresh from the repo, git clone https://github.com/handshake-org/hsd.git
i will remove host.json

**Comment by esmiwuals2** [comment]
all is good

**Comment by esmiwuals2** [comment]
thanks
